### ISSUE TITLE
InterOp Quality Metrics v6

### ISSUE THREAD

**Issue by sklages** [Illumina/interop#104]
Hi,

I am just wondering if the interop format description at one point is not correct:

[Q-Metrics Version 6](http://illumina.github.io/interop/q_v6.html ) says:

`byte 4 - binCount:  array of low ends for each bin (uint8)`

This is way too short.

Isn't it sth like:

`byte 4 - (4 + binCount)`

where `binCount` is `byte 3`?

best,
Sven

**Comment by ezralanglois** [comment]
Yes, you are correct. Bin count is the size, so it should be 4+binCount.

**Comment by ezralanglois** [comment]
I will leave this open until we correct it, at least in master.
