### ISSUE TITLE
Discrepancy on error metric's standard deviation.

### ISSUE THREAD

**Issue by yechenqiao** [Illumina/interop#107]
Hi,
It seems when I computed standard deviation with (n-1) version of formula and last cycle removed, I get a different value for error metric on all lanes and reads. Even though the mean is the same. And the standard deviation of all other metrics matches what's printed out in the summary tab when computed by hand (e.g. via excel).

[stdev.xlsx](https://github.com/Illumina/interop/files/834827/stdev.xlsx)
If you look at this xlsx file, you 'd see that the mean is 0.14, stdev is 0.404

However, using the run folder  https://basespace.illumina.com/run/14858869/HiSeq-2500-v2-TruSeq-Exome-9-replicates-of-NA12878 from basespace, I have different standard deviations on all values when it's printed out with summary binary
[summary.txt](https://github.com/Illumina/interop/files/834829/summary.txt)

So my question is this: is there any difference between the way of computing standard deviation of error metrics than computation of stdev of any other metrics in API? I can't seem to find how they differ at a glance.

Thanks!

**Comment by nudpa** [comment]
Hello Yechen,

The base unit for all the metrics displayed on the summary tab is a tile. In order to calculate the variation in error rate to match SAV, you'd need to aggregate all the cycles for each tile into a tile-level error rate, and then calculate the mean/variance on those values. This way, the variance shows the difference between tiles, as opposed to being dominated by cycle-to-cycle variability.

Please see the documentation here: http://illumina.github.io/interop/error_metrics_requirement.html for more information.

**Comment by yechenqiao** [comment]
Hi nudpa,
Thanks for the quick response. I am currently using the dumptext and I believe the API is already grouping by tiles. i.e.: for each (row, lane) there is only one tile result for error metric.
Is there something else here?
[error.txt](https://github.com/Illumina/interop/files/834874/error.txt)

**Comment by nudpa** [comment]
Hello Yechen,

The InterOp file (and thus, dumptext) reports error rates by lane/tile/cycle. For instance, from your error.txt file above, the first 8 entries come from the same lane/tile (1/1101), but different cycles:

Lane,Tile,Cycle,ErrorRate
1,1101,1,0.231517
1,1101,2,0.108091
1,1101,3,0.123457
1,1101,4,0.0771605
1,1101,5,0.0617284
1,1101,6,0.0771605
1,1101,7,0.0154321
1,1101,8,0.0771605

You'll have to average together the error rates for every entry with the same lane/tile key into a single value to get the inputs for the summary tab's calculations.

Hope that helps.

**Comment by yechenqiao** [comment]
I see that now. The standard deviation computed this way will be consistent with standard deviation computed by tile metrics because they would both by aggregated per lane, tile, and read.
Thanks!
