### ISSUE TITLE
Why summary tables have spaces between the labels and other values?

### ISSUE THREAD

**Issue by nuin** [Illumina/interop#110]
Parsing the summary table becomes a hurdle when all labels are separated by commas and *spaces*. Any automated CSV parser takes the spaces in question and keeps in the labels.

One example if `pandas` `read_csv`, and to access columns you need to strip or name the columns before reading it. Why do that with a CSV file? Is there an option just to not add the spaces at generation time?

Thanks

**Comment by ezralanglois** [comment]
This is a fair point. I look into improving that, likely adding a new option `--csv=1` to enable CSV only writing.

**Comment by nuin** [comment]
Thanks @ezralanglois
