### ISSUE TITLE
Simulator for tile instead of cycle

### ISSUE THREAD

**Issue by tcezard** [Illumina/interop#131]
When we create test runs for our pipeline we usually remove most tile but one to speed up the processing.
In order for the interop to work we would need to have interop that have the same number of tiles as the test run.
Is it possible to create an equivalent of `cyclesim` that would limit the tiles to a specified set?

Cheers
Tim

**Comment by ezralanglois** [comment]
This `cyclesim` and `simulator` are legacy applications  (much like `interop2csv`) that were written early in the development of the library, but we never got around to removing or updating them.

I am not clear on how you are using this program, but `aggregate` may give you something closer to the functionality you are looking for (if you don't need to update the cycle count).

The documentation for this application is lagging, but you can provide it with a `--max-tile=1` flag, this will reduce the output InterOp files such that the tile number will not exceed 1. It won't reduce the InterOps to a single tile, but it will reduce them to 1 per lane/surface/section. 

We could add additional parameters to this one to further filter by those conditions.

The one caveat is that you would need to update the RunInfo.xml yourself at the moment.

**Comment by nudpa** [comment]
Closing out - please feel free to reopen if there are further questions
