### ISSUE TITLE
interop/io/format/metric_format.h::read_header (87)

### ISSUE THREAD

**Issue by golharam** [Illumina/interop#135]
I have my runs mounted via BaseMount and I'm in the "Files" directory of one of my runs.   When I try to run summary or index-summary, I get this error:

index-summary .
# Version: v1.0.8-10-g34a5cd6
Record size does not match layout size, record size: 206 != layout size: 6 for Q  v6
interop/./interop/io/format/metric_format.h::read_header (87)

summary .
# Version: v1.0.8-10-g34a5cd6
Record size does not match layout size, record size: 206 != layout size: 6 for Q  v6
interop/./interop/io/format/metric_format.h::read_header (87)

**Comment by ezralanglois** [comment]
Can you zip up the interop directory and run info and attach them to this ticket? 
I would be happy to dig further into this issue.

Best,
Rob

**Comment by ezralanglois** [comment]
Never mind about the interop files. This is a known bug in this version of the code.

Prior to v1.10, there was a [bug](https://github.com/Illumina/interop/commit/5d76658d526250833e38d2a8d8adb60322a73918) in the Q-metrics version 6 format where it failed to properly parse unbinned q-metrics.

Based on the message above, you are using either some custom version after v1.0.8 or some version between v1.0.8 and v1.0.9.

Also, the more recent versions of the index_summary application will not parse metric files that are unnecessary to its function, e.g. q-metrics.
