### ISSUE TITLE
Python binding for plots

### ISSUE THREAD

**Issue by garrett-stevens** [Illumina/interop#143]
Hi,

I think I've been able to successfully populate a bar plot object using something like:
```python
py_interop_plot.plot_sample_qc(metrics, lane, bar_plot_data)
```
but I haven't been able to figure out how to actually get the data out of the object. Is there a way to interface with the gnuplot_writer.write_chart from Python?

Thanks

**Comment by ezralanglois** [comment]
Hi Garrett,

I created a Gist showing how to get the data out of this object properly here:

<script src="https://gist.github.com/ezralanglois/e80d171f7854c3d0f07a90b83af9adcc.js"></script>

I think we need to improve our documentation in this area both in terms of Python examples and the Modules section. Here is the relevant documentation on necessary classes:

http://illumina.github.io/interop/namespaceillumina_1_1interop_1_1model_1_1plot.html

The Python code is very similar to the C++ code, so you can always look at the C++ unit tests for examples, e.g.

https://github.com/Illumina/interop/blob/master/src/tests/interop/logic/plot_logic_test.cpp#L210

**Comment by ezralanglois** [comment]
I updated the gist link: https://gist.github.com/ezralanglois/e80d171f7854c3d0f07a90b83af9adcc

**Comment by garrett-stevens** [comment]
Thanks so much for this. I have just a couple questions about your Gist:

1. I'm assuming your `bar_data` object is just something you created using
```python
bar_data = py_interop_plot.bar_plot_data()
```
Is that right?

2. In the lines where you are using matplotlib to generate the plot like this one:
```python
x = [bar_data.at(i).at(j).x() for j in xrange(bar_data.at(i).size())]
```
What is the `i` referring to?

Thanks again

**Comment by ezralanglois** [comment]
1. You are correct about `bar_data`. 
2. I made a mistake in the gist, I just updated it. I was missing the following loop
`for i in xrange(bar_data.size()):`

**Comment by garrett-stevens** [comment]
Awesome, I got your Gist to work on my local data. Thanks so much!

**Comment by ezralanglois** [comment]
Great. I will close this out. Please feel free to reopen if you have more questions on this topic or open a new one if you have further questions on something new.

Best,
Rob
