### ISSUE TITLE
How to get the mean q-score per read and lane?

### ISSUE THREAD

**Issue by johandahlberg** [Illumina/interop#145]
Hi!

First of all, thank you for providing this library.

I'm trying to figure out how to get the mean q-score per read and lane using the Python API, and so far I've not been able to figure it out.

For a lot of other metrics e.g. the error rate I'm able to do something like this to access the error rates:
```
run_metrics = py_interop_run_metrics.run_metrics()
run_metrics.run_info()

valid_to_load = py_interop_run.uchar_vector(py_interop_run.MetricCount, 0)
py_interop_run_metrics.list_summary_metrics_to_load(valid_to_load)
run_metrics.read(RUNFOLDER, valid_to_load)

summary = py_interop_summary.run_summary()
py_interop_summary.summarize_run_metrics(run_metrics, summary)

lanes = summary.lane_count()

for read in range(summary.size()):
    for lane in range(lanes):
        mean_error_rate = summary.at(read).at(lane).error_rate().mean()
        print("mean error rate at read: {} and lane: {} is: {}".format(read, lane, mean_error_rate))
```

However to I can't seem to figure out how to extract mean q-score at the same level.

Is it possible to get it? And if so, could you give me some pointers on how to get to it?

Cheers,
Johan

**Comment by ezralanglois** [comment]
The `run_summary` object is essentially the Run Summary in SAV. So any metric not displayed in that SAV tab will not be available.

Also, I am not sure what the mean Q-score provides. In practice, the aligner will just use the Q30 and above bases.  So, % >= Q30 seems like a better metric.

If you really wan this metric, then you can always access the data at a low level
https://github.com/Illumina/interop/blob/master/docs/src/Tutorial_03_Low_Level.ipynb

Just replace `extraction_metric_set` with `q_metric_set` and you can get access to the underlying histogram with `qscore_hist`.

**Comment by johandahlberg** [comment]
Thank for the help. That did clarity things for me, even if I solved this in another way in the end. Feel free to close this issue.
