### ISSUE TITLE
Errors in Interop Python tutorial [Interop v1.0.25, Python 3.6.3]

### ISSUE THREAD

**Issue by mowreyw** [Illumina/interop#154]
When accessing metrics from a run_summary object at a specific read and lane, it seems that I always receive the same mean and median values. For example:

`summary.at(0).at(0).cluster_count().median()` results in `880134.0`
`summary.at(1).at(0).cluster_count().median()` results in `880134.0`
 
Shouldn't these commands give me read-specific values for reads 1 and 2? If not, what is the proper way to get read-specific metrics such as cluster_count and density?

**Comment by ezralanglois** [comment]
The cluster count will not change from read to read. We expect the same value for this metric.

**Comment by mowreyw** [comment]
sorry, i was confused. upon printing them all out I see that some metrics vary in a read-specific way. i was just looking at the wrong ones.
