### ISSUE TITLE
No NuGET packages available for Windows C# users

### ISSUE THREAD

**Issue by pjmlp** [Illumina/interop#155]
While looking for binary packages targeted for Windows, it was not possible to find NuGet packages and Visual C zip files don't provide shared libraries callable from C# (*.dll).

**Comment by ezralanglois** [comment]
Thanks for pointing this out. It looks like our appveyor script either did not generate the nuget files or put them in the wrong location.

I will dig into this and get the nuget packages up in the next release.

**Comment by pjmlp** [comment]
You're welcome, thanks for looking into it.
