### ISSUE TITLE
Interop on PyPI

### ISSUE THREAD

**Issue by johandahlberg** [Illumina/interop#158]
Hi!

Firstly, thanks for providing a great library. I'm maintaining a open source project called [CheckQC](https://github.com/Molmed/checkQC), which depends on Interop. One problem that I've been having is that Interop cannot be installed from PyPI. Most recently my problem is related to getting our documentation up on ReadTheDocs, but we have also seen one user who cannot install our software because they have they have trouble install Interop. Having the library installable via PyPI should be helpful to all users utilizing Interop via the Python APIs.

I'm therefore wondering if it would be possible for you to upload Interop to PyPI? If there is any support I can provide to make that happen let me know.

Cheers,
Johan

**Comment by ezralanglois** [comment]
Hi Johan,
We have had this item in the back log for a while. We want to ensure that it is kept up to date with every new release for Linux, Mac and Windows.

I will move this up in priority.

Best,
Rob

**Comment by johandahlberg** [comment]
That's great to hear! Looking forward to it. :smile:

**Comment by ezralanglois** [comment]
It should be supported from now on, the libraries will be up hopefully by the end of the day.

**Comment by johandahlberg** [comment]
Thanks! It works great! :smile:
