### ISSUE TITLE
dumpbin error - unhelpful error message 

### ISSUE THREAD

**Issue by sfpacman** [Illumina/interop#159]
I am trying to run dumpbin to covert bin files to text but return the following error: 
```
src/apps/dumpbin  /path/to/runfolder
# Version: v1.1.2
terminate called after throwing an instance of 'std::length_error'
  what():  vector::_M_fill_insert
Aborted (core dumped)
```
I have just compiled the interop from the source, so it can be installation error, but I have no way to know  based on the error message

**Comment by ezralanglois** [comment]
Hi,
I would suggest the following to help debug this issue:

1. Try the Linux build (it looks like you are on Linux) -> if that works, then it was a compile issue
2. Try loading the data in SAV -> if that does not work, then the interop data is corrupted
3. Could you Provide the InterOps and RunInfo.xml? That would help me dig into this issue further.

Best,
Rob

**Comment by ezralanglois** [comment]
This issue seems to be linked with https://github.com/Illumina/interop/issues/165

I can be worked around by using the precompiled version of InterOp.
