### ISSUE TITLE
Add percentage of used clusters by lane in summary output (NovaSeq)

### ISSUE THREAD

**Issue by a-perin** [Illumina/interop#163]
Hi, 
Is it possible to add the percentage of clusters on the lane that are occupied in summary output command (if  ExtendedTileMetricsOut.bin file exist in InterOp directory) ?
We haven't developed our process in Java, it is difficult for us to use the defined class.
Kind regards,
Aurélie.

**Comment by ezralanglois** [comment]
Hi Aurélie,

I just want to make sure I understand correctly. You want the percent occupied for each lane to be printed in the command-line summary application?

Best,
Rob

**Comment by ezralanglois** [comment]
Or, are you using the Java-binding for the code?

**Comment by ezralanglois** [comment]
Sorry for the confusion. I just remembered that there is no Java binding, we only support C# and Python at the moment.

**Comment by ezralanglois** [comment]
Hi Aurélie,

I think I answered my own questions. We do plan to add % occupied to the summary application, but that will take some time.

For now, the best way to get the information is using the `plot_by_lane` command line application.

`plot_by_lane <run-folder> --metric-name=PercentOccupied`

> # Version: v3.3.4-iuo
> # Run Folder: 160812_VP1-09_0165_BH0GNDMCVY-goodDC
> set terminal png crop
> set output '160812_VP1-09_0165_BH0GNDMCVY-goodDC_PercentOccupied-by-lane.png'
> set title "03WPCAAVY"
> set yrange [0 : 111.275 ]
> set ylabel "% Occupied"
> set xrange [0 : 2 ]
> set xlabel "Lane"
> set datafile separator ","
> set boxwidth 0.3
> plot "-" using 1:3:2:6:5 with candlesticks title "% Occupied" lt rgb "blue" whiskerbars
> 1,92.7288,92.7288,92.7288,92.7288,92.7288
> e

The section you will be interested in with begin after the `plot` where the first number is the lane and the forth is the median percent occupied.
For completeness:
Lane,Min_PercentOccupied,P25_PercentOccupied,Median_PercentOccupied,P75_PercentOccupied,Max_PercentOccupied

**Comment by a-perin** [comment]
Hi Rob,

I thank you for your answers.

Indeed, I would the percent of clusters occupied for each lane to be printed in the command-line summary command line application ("summary <run_folder>").
Can you tell me when you can do it please?
I thank you in advance :)

I tested plot_by_lane command line application as you proposed. But I have an error message :

plot_by_lane 171212_EXTNOVASEQ_H2VHCDMXX --metric-name=PercentOccupied
# Version: v1.0.25-31-g51eb4ca-dirty
Unsupported metric type: PercentOccupied
/tmp/wiart-reforge/BUILD/interop-1.0.25.20170831git/src/interop/logic/utils/metrics_to_load.cpp::list_metrics_to_load (99)

I use 1.0.25 version of InterOp. The problem surely come from there. Which version should I need to use?

Kind regards,
Aurélie.

**Comment by a-perin** [comment]
The answer to my question is in your previous post: I need to use the version 1.1.3 ;)
Thanks !!

**Comment by ezralanglois** [comment]
Hi Aurélie,

It is in our backlog, but I have no ETA at the moment on when we will get to it. I will leave this open until we do, so that you will be notified when it goes in.

Best,
Rob

**Comment by philipbohannon** [comment]
Hi @ezralanglois , is there any update on if/when `PercentOccupied` and/or `OccupiedCountK` will be added to the `summary` tool?

**Comment by ezralanglois** [comment]
No update yet, it is in our plan but it is low priority at the moment. 

Linked to this issue: https://github.com/Illumina/interop/issues/193

**Comment by sklages** [comment]
Well, I am also interested in that `summary` extension. :-)

**Comment by sklages** [comment]
hm, okay, `plot_by_lane` works like a charm :+1:
