### ISSUE TITLE
[Question] Is there any options for convert 'e+xx' to integer?

### ISSUE THREAD

**Issue by scarleaf** [Illumina/interop#166]
Hi, 
I'm try to use 'dumptext' program, but output text have expression 'e+xx'.
Please let me know if there are some solutions.
Thank you all.

**Comment by ezralanglois** [comment]
Hi,

I am not sure I follow, maybe you could provide an example to clarify the problem? 

Many of the values are floating point, and we store them in the scientific notation to ensure that the text file does not become bloated with unnecessary 0's. 

The conversion to an integer would, in most cases, cause data loss (depending on how you implemented it). It does not seem like a feature that would be within the scope of dumptext.

Best,
Rob

**Comment by ezralanglois** [comment]
There does not seem to much movement on this question. Closing it out.
Feel free to reopen.
