### ISSUE TITLE
Pip Install Question

### ISSUE THREAD

**Issue by newbiebook** [Illumina/interop#169]
Hi, 
I'm new to python and the new Interop. I've installed one of the wheel library, interop-1.1.3-cp36-cp36m-win_amd64, by 'pip install' command. It looked successful. And the test ran okay without error. I then located the packages installed at ...Python36\Lib\site-packages with subfolders such as:
interop
interop-1.1.3.dist=info
...
But none of these seem to contain an executable that can be used the way the previous 'interop2csv' was used. I'm expecting to see an application or executable that can be used in command line. Is there any problem with my pip install? Any other options shall I try? 

Thanks!

**Comment by ezralanglois** [comment]
No, your install is working as intended. We do not include the applications as a part of the Python install. If you need those applications, then you should download the zip or gz archives.

Best,
Rob

**Comment by newbiebook** [comment]
Thanks so much for the quick response! But I also tried InterOp-1.1.3-Windows-MSVC.zip from the Release list, but it doesn't contain an application. Is it supposed to have a 'bin' directory?

**Comment by newbiebook** [comment]
As I mentioned above, I also tried .zip file but it doesn't contain an application. 

We need an application like 'interop2csv' so that we can call from command line, or call as external program in java code:

C:\InterOpParsing\interop-msvc14_win64_Release\bin\interop2csv  [run directory] > [destination directory]

What's your suggestion? Do we have to build from the Source Code?

Thanks!

**Comment by newbiebook** [comment]
The InterOp-1.1.3-Windows-MSVC.zip does not contain 'bin' directory, which is expected to contain the dumptext command line tool. Can you please look into it? 

Thanks!

**Comment by ezralanglois** [comment]
This was an issue we fixed recently. I just kicked off a new release v1.1.4, which should have these missing applications.

Best,
Rob

**Comment by newbiebook** [comment]
Great, thank you, Rob! But you'll be having a windows zip file in the list soon, right? Hope that'll be available because we don't use source code here. 
Thanks!
Tong

**Comment by ezralanglois** [comment]
If there are no unexpected issues, then it should be up in the afternoon. You can click on the Appveyor link on the front page read me if you need an estimate.

Best,
Rob

**Comment by newbiebook** [comment]
Many thanks, Rob! I've downloaded the windows zip file...will start from there. I'll let you know if we run into any other issues using this new script. 
Best,
Tong
