### ISSUE TITLE
InterOp file update during bcl2fastq

### ISSUE THREAD

**Issue by sklages** [Illumina/interop#172]
It seems that at least `IndexMetricsOut.bin` is updated during bcl conversion with `bcl2fastq`.

1. what happens if the directory or the file is read-only for the user running `bcl2fastq`?
1. when I run three demultiplexing jobs (each of these using different lanes of the run or simply different parameters or samplesheets) on the same run data (bcl files). How is updating of `IndexMetricsOut.bin` working?

I want to write a little demux reporting script and was wondering wether it's better to use `Stats.json` or fetch some data using `interop binaries`. 

Is `interop/apps/summary` the only way to get `aligned` (PhiX) results? This seems not to be recorded in neither `Stats.json` and `DemultiplexingStats.xml`.

**Comment by ezralanglois** [comment]
Hi,

If the bcl2fastq cannot write the InterOp file, then in some versions it will stop with an error and others it will just log a warning.

Two or more bcl2fastq jobs will not communicate with each other, so likely the output InterOp and stats file (if all the jobs are pointed at the same output folder) will just be corrupted.

You could use the InterOp library to combine all the InterOp files into a single file (assuming all the bcl2fastq jobs are pointing to different output directories).

The % aligned data is produced by RTA not bcl2fastq. So you will not find the data in the bcl2fastq outputs.

Also, the InterOp library only reads InterOp files (RunInfo.xml and RunParameters.xml), not the XML or Json files produced by bcl2fastq.

Hope this helps.

**Comment by sklages** [comment]
Thanks for clarification.

>If the bcl2fastq cannot write the InterOp file, then in some versions it will stop with an error and others it will just log a warning.

I'd prefer the latter :wink:

>Two or more bcl2fastq jobs will not communicate with each other, so likely the output InterOp and stats file (if all the jobs are pointed at the same output folder) will just be corrupted.

It is not very uncommon to have a mixed flowcell e.g. with one `TruSeq 6nt index` fraction and another `Nextera 8nt dual-index` fraction, sometimes on distinct lanes, sometimes even mixed in one single lane. Not optimal, but if barcodes are compatible I don't see any problem.

For the 6nt barcodes I'd use `y75n,i6n*,n*,y75n` and for the di-8nt barcodes I'd use `y75n,i8n,i8n,y75n` for a PE76 run (`y76,i9,i9,y76`). This is done in two separate bcl2fastq jobs as this cannot be done in a single one AFAIK. And of course each of the jobs with its own outfolder. But the source (run) folder is the same. This means, both jobs will "update" the interop file. If this is done at the end of demultiplexing, than the interop file contains the results of the slowest job. If this is done during demultiplexing the interop file is probably corrupted.

OK, so for me it is safer to use `Stats.json` to compile demux results as this resides always in a separate results folder and corresponds to one single bcl2fastq job.

>The % aligned data is produced by RTA not bcl2fastq. So you will not find the data in the bcl2fastq outputs.

OK, this makes perfectly sense :-)
