### ISSUE TITLE
Q: Error while running examples

### ISSUE THREAD

**Issue by passanger** [Illumina/interop#173]
Hi,
I have some problem when i try to see how inteop examples works.
Basically i want to connect [miso lims](https://github.com/TGAC/miso-lims/tree/master) with runscanner-illumina (interop)
I am using [nova seq 6000 output sample](https://basespace.illumina.com/run/62203141/NovaSeq-6000-TruSight-Oncology-UMI-Reagents-with-TST170-DNA-LoVo-or-Horizon-mixtures-in-NA12877-) (dowloaded on my local machine - **mac**)
Path to file: `/Users/Passanger/Documents/programming/tools/tomcat8/conf/Catalina/localhost/storage/miso/files/sequencer/OutputFolders/test-serial-number-2/`
Results:
1. **example1** `Tile metric set contains 1408 metrics`
2. **example2** `Lane: 1
Tiles 704
Cluster PF (%): 75.1708
Lane: 2
Tiles 704
Cluster PF (%): 76.1592`
3. **example3** `Time: 01/01/1970 12:00:00 AM`
4. **example4** `Mean of percent base for A 25.358
Standard Deviation of percent base for A 3.24831
Mean of no call0.163556`
 4. **example_q_metric** `Total >= Q30: 2878245
Percent >= Q30: 93.1903`
5. the problematic one: **example_populate_qmetricset** `Segmentation fault: 11`

As i see, the problem is when it tries to execute some method of the "run_metrics" class.
For example 
```
run_metrics metrics;
metrics.clear(); 
```

Can someone help me to understand whats going on?

**Comment by ezralanglois** [comment]
Yes, this example got mangled for some reason that is unclear to me.
We will put out a pull request to fix this, but before that I can show you the proper lines that should be there:

`std::vector<unsigned char> valid_to_load(constants::MetricCount, 0);
    valid_to_load[constants::Q]=1;
    run_metrics metrics;`

The 3 lines above should replace the problematic ones below:
`std::vector<unsigned char> valid_to_load;
    valid_to_load[constants::Q]=1;
    run_metrics metrics;
    metrics.clear();`

The code segfaulted because we indexed into an empty std::vector (valid_to_load).

**Comment by passanger** [comment]
Hi ezralanglois ,
Thanks for the ansfer.
After these changes, i've successfully started **example_populate_qmetricset** example.
I've also made these changes in  [miso/runscanner-illumina main.cpp](https://github.com/TGAC/miso-lims/blob/develop/runscanner-illumina/main.cpp)
it looks like:
`std::vector<unsigned char> valid_to_load(illumina::interop::constants::MetricCount, 0);
   valid_to_load[illumina::interop::constants::Q]=1;
   illumina::interop::model::metrics::run_metrics run;`

and i changed `run.read(argv[1]);` to `run.read(filename, valid_to_load);` where _filename_ is `   std::string filename(argv[1]);`

And when i compile and start **./runscanner_illumina**  i'am not receiving 'Segmentation fault: 11' but another error occurs `runscanner-illumina(58911,0x7fff8c810380) malloc: *** error for object 0x7ffee084eff8: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6`
This error occurs when read method is called `run.read(filename, valid_to_load);`

Maybe you can help me with this?

**Comment by ezralanglois** [comment]
Do you have the code pushed up to a branch? I don't see these changes in your develop branch.

**Comment by ezralanglois** [comment]
Please open a new issue for this bug. 
Thanks.
