### ISSUE TITLE
Miso lims integration with illumina interop dosn't work

### ISSUE THREAD

**Issue by passanger** [Illumina/interop#176]
Hi, 

I've try to setup [miso lims](https://github.com/TGAC/miso-lims) with illumina interop,
There is how to connect interop with miso [(link)](https://github.com/TGAC/miso-lims/tree/develop/runscanner-illumina)
Examples that i'am using (downloaded from illumina):
1. [first](https://basespace.illumina.com/run/62203141/NovaSeq-6000-TruSight-Oncology-UMI-Reagents-with-TST170-DNA-LoVo-or-Horizon-mixtures-in-NA12877-)
2. [second](https://basespace.illumina.com/run/70447381/NovaSeq_96_UDI_TS_DNA_LP_ENR_with_IDT_xGen_Exome)

Path to this examples on my local machine:
-`/Users/Passanger/Documents/programming/tools/tomcat8/conf/Catalina/localhost/storage/miso/files/sequencer/OutputFolders/test-serial-number-1/`
-`/Users/Passanger/Documents/programming/tools/tomcat8/conf/Catalina/localhost/storage/miso/files/sequencer/OutputFolders/test-serial-number-2/`

this is how i run the illumina from miso:
`./runscanner-illumina /Users/Passanger/Documents/programming/tools/tomcat8/conf/Catalina/localhost/storage/miso/files/sequencer/OutputFolders/test-serial-number-2/`

I have no specific branch, i've just tried with miso from **master branch**, and with **latest** version of ilumina interop

There are two errors that occurs, 
1. `Segmentation fault: 11` which is resolved i guess with [#173](https://github.com/Illumina/interop/issues/173)
2. `runscanner-illumina(58911,0x7fff8c810380) malloc: *** error for object 0x7ffee084eff8: pointer being freed was not allocated *** set a breakpoint in malloc_error_break to debug Abort trap: 6` when `run.read(argv[1]);` has been called.

Can someone help me?
Thanks

**Comment by passanger** [comment]
Also, i've tried to replace entire main.cpp with **example_populate_qmetricset.cpp** (example with fixed `Segmentation fault 11` issue), but `Segmentation fault 11` occurs again...
Maybe its related to way how runscanner-illumna is builded and compiled on miso...

**Comment by ezralanglois** [comment]
miso lims uses a git submodule when pointing to Interop. The submodule is likely pointing to the old version of interop unless you updated it. I personally find the git submodules clunky to work with.

This is the main function that is currently segfaulting?
https://github.com/TGAC/miso-lims/blob/develop/runscanner-illumina/main.cpp

Best,
Rob

**Comment by passanger** [comment]
I've tried with both version of linterop, with pulled from submodule, and with latest one from your repository.

> This is the main function that is currently segfaulting?
https://github.com/TGAC/miso-lims/blob/develop/runscanner-illumina/main.cpp
Yes, the main function segfaulting, `run.read(argv[1]);`

**Comment by ezralanglois** [comment]
I suggest running it through valgrind.
