### ISSUE TITLE
Extraction metrics missing dates on NovaSeq

### ISSUE THREAD

**Issue by apmasell** [Illumina/interop#177]
We've been using the extraction metrics `illumina::interop::model::metrics::extraction_metric.date_time()` to determine when a run was completed (per the examples). This does not seem to work correctly on NovaSeq runs. We have a NovaSeq run with a 5.7MB `InterOp/ExtractionMetricsOut.bin` file, but when using the interop library, the extraction dates are 0 for all the metrics.

What is the correct method to get the completion date for a run? Thank you.

**Comment by ezralanglois** [comment]
The InterOps were designed to convey metrics that describe the sequencing performance of a run. Extraction cycle time is really not a performance metric and is available in many other forms. So, we removed this value from extraction metrics.

A more complete run time profile can be generated from the various logs available in the run folder.

**Comment by apmasell** [comment]
Okay. Thanks!
