### ISSUE TITLE
Missing/Additional InterOp files

### ISSUE THREAD

**Issue by jelichi** [Illumina/interop#181]
Hello, I am pretty new to looking at InterOp files, and after going through the documentation it looks like my runs folders are missing some files. This is what exists in my run folders:

CorrectedIntMetricsOut.bin
ErrorMetricsOut.bin	
ExtractionMetricsOut.bin
QMetricsOut.bin		
TileMetricsOut.bin
EmpiricalPhasingMetricsOut.bin	
EventMetricsOut.bin
PFGridMetricsOut.bin
RegistrationMetricsOut.bin

According to the InterOp documentation, I should also be expecting to see these file which do not exist:
ImageMetricsOut.bin
IndexMetricsOut.bin
QMetrics2030Out.bin
QMetricsByLaneOut.bin
ExtendedTileMetricsOut.bin

I am particularly interested in using the QMetrics2030Out.bin file. How is this generated? 

Also, these files are not expected, is there any existing documentation for them?
EventMetricsOut.bin
PFGridMetricsOut.bin
RegistrationMetricsOut.bin

I'm using version v1.1.4-4-gf87d6ef

**Comment by nudpa** [comment]
Hello Jenn,

The InterOp code is built to be compatible with all recent Illumina platforms. However, depending on your workflow and the platform you are running, you may only get a subset of the supported InterOp files. For instance, QMetrics2030Out.bin is typically generated in BaseSpace from the data in the QMetricsOut.bin file, using the logic here: https://github.com/Illumina/interop/blob/master/src/interop/logic/metric/q_metric.cpp#L189.

The other files you noticed are only meant for internal use, and are thus not publicly documented.
