### ISSUE TITLE
Full documentation for python interop parser

### ISSUE THREAD

**Issue by BCArg** [Illumina/interop#186]
Is there a full documentation for the illumina interop python module?.

I could find five walk-through examples in this github page, but it appears that the python module can do much more than the examples show. Also, the examples do not really explain the commands.

From the binary files generated under the interop folder, I would like to parse the following information

1. Percentage of clusters >= Q30
2. Base calling error rate
3. Percentage of reads passing filter
4. Percentage of phiX that was recovered

Thanks in advance

**Comment by johandahlberg** [comment]
Not exactly what you are asking for, but for the first two items on your list I have written some code in our project CheckQC to do that: https://github.com/Molmed/checkQC/blob/9ec1e20c510e987b05f49a8a1e8d6a3db2a358ff/checkQC/parsers/interop_parser.py#L63
I'm sure that the folks over at Illumina can give you a better answer, but I saw this, and thought perhaps this could be a little help on the way.

**Comment by BCArg** [comment]
Thanks for your reply, I'm going through the available documentation and the only metrics missing as of now is the percentage of phiX that was recovered

**Comment by johandahlberg** [comment]
@BCArg The issue of getting percentage of PhiX recovered actually came up here just now, so I had a quick look at it.

I'm not 100% sure I've got it right, but here is how I was able to access it. I've copied some of the code surrounding it from CheckQC, so that you see which context it is loaded in:
```
        run_metrics = py_interop_run_metrics.run_metrics()
        run_metrics.run_info()

        valid_to_load = py_interop_run.uchar_vector(py_interop_run.MetricCount, 0)
        py_interop_run_metrics.list_summary_metrics_to_load(valid_to_load)
        run_metrics.read(self.runfolder, valid_to_load)

        summary = py_interop_summary.run_summary()
        py_interop_summary.summarize_run_metrics(run_metrics, summary)

        lanes = summary.lane_count()
        reads = self.get_non_index_reads(summary)
        for lane in range(lanes):
            # The interop library uses zero based indexing, however most people uses read 1/2
            # to denote the different reads, this enumeration is used to transform from
            # zero based indexing to this form. /JD 2017-10-27
            for new_read_nbr, original_read_nbr in enumerate(reads):
                read = summary.at(original_read_nbr).at(lane)
                error_rate = read.error_rate().mean()
                percent_q30 = read.percent_gt_q30()
                # THE INTERESTING PART
                aligned = read.percent_aligned().mean()
```

I think that should get you the mean number of PhiX recovered across all tiles for the lane for that read (https://github.com/Illumina/interop/blob/044fbc86ec32b3c079af37ad57f5ceae273d1c5c/interop/model/summary/stat_summary.h#L173).

**Comment by ezralanglois** [comment]
Hi John,

Thanks for answering this. You are correct, this is essentially what we do in SAV.

**Comment by johandahlberg** [comment]
@ezralanglois no problem! Thanks for providing the python APIs. One thing that I think would be great to highlight is the possibility to do `dir(<python swig object instance>)` to see which methods/fields it has. That has helped me a lot when debugging. I'm not sure how clear that is in the docs right now.

**Comment by ezralanglois** [comment]
Interesting. I have not tried that myself, but I am happy to call that out in the next release of the docs.

I think the documentation has been a pain point in this code base, mostly given the number of languages supported. Our goal is to continue adding examples (or links to projects that can serve as examples)

**Comment by BCArg** [comment]
Thanks for the answers. As explained [here](https://www.biostars.org/p/346675/#346782), running `$ interop_summary` (on the terminal) will automatically parse the summary from SAV. I then wrote a python script to extracts the metrics that I wanted.

**Comment by ezralanglois** [comment]
Improving the documentation for Python is a goal we will work toward:

I added a little more information here:
http://illumina.github.io/interop/python_binding.html
