### ISSUE TITLE
Error message on Tutorial_04_Indexing_Metrics.ipynb

### ISSUE THREAD

**Issue by BCArg** [Illumina/interop#187]
I am going through all the tutorials and on the above mentioned one, when I run the following command:

columns = ( ('Index Number', 'id'), ('Sample Id', 'sample_id'), ('Project', 'project_name'), ('Index 1 (I7)', 'index1'), ('Index 2 (I5)', 'index2'), ('% Reads Identified (PF)', 'fraction_mapped'))
lane_summary = summary.at(0)

```
columns = ( ('Index Number', 'id'), ('Sample Id', 'sample_id'), ('Project', 'project_name'), ('Index 1 (I7)', 'index1'), ('Index 2 (I5)', 'index2'), ('% Reads Identified (PF)', 'fraction_mapped'))
lane_summary = summary.at(0)

d = []
for label, func in columns:
    d.append( (label, pd.Series([getattr(lane_summary.at(i), func)() for i in range(lane_summary.size())], index=[lane_summary.at(i).id() for i in range(lane_summary.size())])))
df = pd.DataFrame.from_items(d)
df
```

I get the following error message:

`Lane index exceeds lane count - 0 >= 0`

All the commands before those ones run without problems. I have downloaded the [Miseq example dataset](https://github.com/Illumina/interop/releases/download/v1.0.6/MiSeqDemo.zip) and my `run_folder` points to the directory where the files were extracted.

**Comment by nudpa** [comment]
Hello @BCArg, thanks for the report. In order to get a meaningful indexing summary, we require a run folder for which demultiplexing has been performed (i.e. with an "IndexMetricsOut.bin" file in the InterOp subfolder). The MiSeq demo you've downloaded does not have that. Could you retry on a run folder that has this file?
