### ISSUE TITLE
interop 1.1.7 for mac OS X and python 3.7

### ISSUE THREAD

**Issue by djevremovic** [Illumina/interop#190]
Would you be able to post the wheel distribution for Mac OS X and Python 3.7. I can see that you have it for Win and Linux, but not for Mac OS X, while for previous versions of python (<3.7) you have all three.

Thank you!
DJ 
Software Engineer
New York Genome Center

**Comment by ezralanglois** [comment]
I will dig into this further, but I found the following:

It looks like the `pyenv` available on OSX with `brew` does not contain python 3.7. It has a beta release. We are already running `brew update && brew upgrade pyenv`.

https://travis-ci.org/Illumina/interop/jobs/460553878

  python-build: definition not found: 3.7.0
  The following versions contain `3.7.0' in the name:
    3.7.0b3
    miniconda-3.7.0
    miniconda3-3.7.0
  See all available versions with `pyenv install --list'.
  If the version you need is missing, try upgrading pyenv:
    brew update && brew upgrade pyenv

**Comment by ezralanglois** [comment]
Got a fix out. It seems to work. After merging this in, I will tag a new release.

**Comment by djevremovic** [comment]
Thank you!!
