### ISSUE TITLE
Comment about installation instructions

### ISSUE THREAD

**Issue by cwarden45** [Illumina/interop#192]
Hi,

Thank you very much for putting this together.

I was able to successfully compile "**From Source**" (and the "dumptext", "summary", and "imaging_table" command-line options worked for a test run).

However, I think there is a typo on the main page (https://github.com/Illumina/interop):

"**cmake ../interop**" should be "**cmake ..**"

Thanks again,
Charles

**Comment by nudpa** [comment]
Hello Charles, thanks for pointing this out - we will fix this line

**Comment by splaisan** [comment]
the typo is still there, thanks @cwarden45 
and on my RHEL7 machine I had to install cmake3 next to my RHEL installed version2 (_yum install cmake3_) then replace 'cmake' in the build commands by 'cmake3'
after which it did build! but did not create a bin folder to put executables (although they seem to live in build/src/apps

should I run an additional make install in /src/apps ?
thanks for your help

**Comment by cwarden45** [comment]
Thank you for your reply!

I think you had to do something a little more complicated, but I hope people can find these two possible solutions if they run into issues (or they at least fix the typo on the page page, for the shorter instructions).

**Comment by ezralanglois** [comment]
````
$ git clone https://github.com/Illumina/interop.git
$ mkdir build
$ cd build
$ cmake ../interop
$ cmake --build .
```
This all looks correct to me. Now, if we had done (cd interop), then the following would be correct:
```
$ git clone https://github.com/Illumina/interop.git
cd interop
$ mkdir build
$ cd build
$ cmake ..
$ cmake --build .
```
