### ISSUE TITLE
How to get percent occupied from iSeq?

### ISSUE THREAD

**Issue by billytcl** [Illumina/interop#193]
I'm trying to get the "% Occupied" while following the tutorial on https://github.com/Illumina/interop/blob/master/docs/src/Tutorial_05_Imaging_Table.ipynb. Using the latest version of the package with Python (2.7) bindings.

However, it seems like that column does not exist in iSeq data. That field appears when I'm parsing out a NovaSeq run but seems to be missing with the iSeq. The information seems to be there (at the very least it is hidden somehow), as I can see it on BaseSpace. I've tried parsing the InterOp folder generated locally as well as one downloaded from BaseSpace, but neither of them give me "% Occupied" as a column to select. How do I go about extracting this information?

**Comment by nudpa** [comment]
Hello Billy, thanks for pointing this out. Support for occupancy on the iSeq should be part of the next update to this repository.

If you need something before then, the file format for v1 ExtendedTileMetrics is pasted below:
byte 0: file version number (1)
byte 1: length of each record (10)
bytes (N * 10 + 2)  - (N *10 + 11): record:
        2 bytes: lane number (uint16)
        2 bytes: tile number (uint16)
        2 bytes: metric code (uint16)
        4 bytes: metric value (float)
where N is the record index and possible metric codes are:
        code 0: number of clusters occupying wells on a patterned flowcell
