### ISSUE TITLE
Python package for python-alpine docker image

### ISSUE THREAD

**Issue by olingerc** [Illumina/interop#194]
Hi,

Recently I've tried to dockerize a python app that uses interop. Many people use the python-alpine images because they are very lightweight. To my surprise the python 3.6 interop manylinux wheel from pypi is not compatible with that distribution (v 1.1.8). Just FYI, I've switched to a "regular" python image.

**Comment by ezralanglois** [comment]
This might be a workaround for the problem: https://github.com/pypa/pip/issues/3969
It looks like manylinux checking logic does not support Alpine.

**Comment by olingerc** [comment]
Indeed! This worked:
```RUN touch /usr/local/bin && echo "manylinux1_compatible = True" > /usr/local/bin/_manylinux.py```
Thanks
