### ISSUE TITLE
How to parse "%Intensity Cycle 20" and "Avg Q Score"

### ISSUE THREAD

**Issue by sunilmakwana** [Illumina/interop#195]
I am able to parse all sequencing metrics as shown in the SAV Summary tab. In addition to these, we also want to know "%Intensity Cycle 20" and "Avg Q Score". Can someone please write a pseudo code on how to extract these metrics or give a pointer on how to do this? 

I saw a similar question here: https://github.com/Illumina/interop/issues/145, but couldn't really figure out how to use the low level metrics to calculate above. 

Thanks in advance!

**Comment by ezralanglois** [comment]
Hi,

These are deprecated metrics we removed because they don't have any real value. I would suggest looking at `% >= Q30` as an alternative to `Avg Q Score`. 

To get intensity, I suggest using the plotting code:
`
    plot_data = py_interop_plot.candle_stick_plot_data()
    options = py_interop_plot.filter_options(run_metrics.run_info().flowcell().naming_method())
    options.surface(surface)
    options.lane(lane)
    py_interop_plot.plot_by_cycle(run_metrics, "Intensity", options, plot_data)
    for read_index in range(run_metrics.run_info().reads().size()):
        if run_metrics.run_info().reads()[read_index].is_index(): continue
        first_cycle = run_metrics.run_info().reads()[read_index].first_cycle()
        last_cycle = run_metrics.run_info().reads()[read_index].last_cycle()
        for i in range(plot_data.size()):
            y = [plot_data.at(i).at(j).y() for j in range(plot_data.at(i).size()) if plot_data.at(i).at(j).x() <= last_cycle and plot_data.at(i).at(j).x() >= first_cycle]
`

**Comment by ezralanglois** [comment]
Closing this out
