### ISSUE TITLE
Extract % Q30 by read by index

### ISSUE THREAD

**Issue by theguipagui** [Illumina/interop#196]
Hi,
I tried to extract %>=Q30 by read by index, but i'm unable to get this information. 
Have you a trick, to resolve it or it's not planned to do this ?
Thanks for your work,

**Comment by nudpa** [comment]
Hello Guillaume, in most of our sequencers, the sample demultiplexing happens after the run has finished sequencing. As a result, RTA has no knowledge of which clusters belong to which sample/index sequence while it's processing, and it can not print out metrics like %>=Q30-by-index.

This information should be available from a bcl2fastq or sequence aligner report, though.

**Comment by theguipagui** [comment]
Thanks
