### ISSUE TITLE
failed to call interop_summary when having Repeated read number at RunInfo.xml

### ISSUE THREAD

**Issue by BCArg** [Illumina/interop#197]
Dear all, 

I am using the `interop_summary` shell command to parse run statistics information from Novaseq runs. 

For some runs, however, we need to modify the RunInfo.xml file: wee need to split split the number of base pairs in read 2. 

Below is a snippet  of the original RunInfo.xml file:
```

<?xml version="1.0" encoding="utf-8"?>
<RunInfo Version="5">
	<Run Id="190621_A00154_0260_AHKH2VDMXX" Number="260">
		<Flowcell>HKH2VDMXX</Flowcell>
		<Instrument>A00154</Instrument>
		<Date>6/21/2019 5:52:16 PM</Date>
		<Reads>
			<Read Number="1" NumCycles="101" IsIndexedRead="N"/>
			<Read Number="2" NumCycles="14" IsIndexedRead="Y"/>
			<Read Number="3" NumCycles="7" IsIndexedRead="Y"/>
			<Read Number="4" NumCycles="101" IsIndexedRead="N"/>
```

And here I am displaying the modified version of the RunInfo.xml:

```
<?xml version="1.0" encoding="utf-8"?>
<RunInfo Version="5">
	<Run Id="190621_A00154_0260_AHKH2VDMXX" Number="260">
		<Flowcell>HKH2VDMXX</Flowcell>
		<Instrument>A00154</Instrument>
		<Date>6/21/2019 5:52:16 PM</Date>
		<Reads>
			<Read Number="1" NumCycles="101" IsIndexedRead="N"/>
			<Read Number="2" NumCycles="8" IsIndexedRead="Y"/>
			<Read Number="4" NumCycles="6" IsIndexedRead="N"/>
			<Read Number="3" NumCycles="7" IsIndexedRead="Y"/>
			<Read Number="4" NumCycles="101" IsIndexedRead="N"/>
```
We can see that, in the snipped above, there is two times the `Read Number="4"`, which throws the following error when I run my script with the `interop_summary`:

`Repeated read number: 4
/opt/conda/conda-bld/illumina-interop_1544151035362/work/src/interop/model/run/info.cpp::validate (342)`

Is there a way to ignore (e.g. via an argument that I pass to the the shell command) this such that the command can run until its end?

**Comment by ezralanglois** [comment]
Hi Bruno,

The underlying assumption of most software that consumes the RunInfo.xml is that the Read Number is unique. 

Even if work workaround this assumption, there likely will be other things that break downstream because this assumption was violated.

From the prospective of the InterOp library, numbering from 1-6 should work.
