### ISSUE TITLE
fastest way to calculate per cycle >= Q30 in python

### ISSUE THREAD

**Issue by twieland** [Illumina/interop#198]
Hi,

I'm trying to get the % >=Q30 per cycle for a whole flowcell in python. Currently I'm trying to sum up the values for each lane and tile per cycle from a set of run_metrics.q_metric_set().qmetrics.metrics_for_cycle(cycle) objects, but python keeps crashing.

Is there a smarter/faster way to do that?

**Comment by nudpa** [comment]
Hello @twieland, have you considered the plot_by_cycle logic? It should go something like:

plot_data = py_interop_plot.candle_stick_plot_data()
options = py_interop_plot.filter_options(run_metrics.run_info().flowcell().naming_method())
py_interop_plot.plot_by_cycle(run_metrics, "Q30Percent", options, plot_data)

where the output (plot_data) is pretty much what SAV displays in its "Data by Cycle" graph.

**Comment by twieland** [comment]
works like a charm, thanks!
