### ISSUE TITLE
QScore Distribution Plot 

### ISSUE THREAD

**Issue by vineetpatel** [Illumina/interop#199]
Hello, I want to extract the information for each lane (not All lanes, but individual lanes) at QScore 30 (>=Q30) (along with the size (in G) and the percentage), which is displayed under the QScore Distribution plot and by setting the slider to QScore 30 (please see the attachment). This information is available when the file is analysed via Sequencing Analysis Viewer software under the analysis tab. However, is there a script to extract it through python? 

![SAV_Analysis_tab (002)](https://user-images.githubusercontent.com/36762962/64966507-cb5bdd00-d896-11e9-9120-63621ede35ec.jpg)

**Comment by ezralanglois** [comment]
The function you want is this one:

`
options = py_interop_plot.filter_options(run.run_info().flowcell().naming_method())
data = py_interop_plot.bar_plot_data()
boundary = 30
py_interop_plot.plot_qscore_histogram(run, options, data, boundary)
`

**Comment by vineetpatel** [comment]
@ezralanglois (Dr Langlois), thank you for your reply. However, I don't want to plot the graph. I just want to extract the numbers (for e.g. 37.6G and 93.1% for individual lane (Lane1)), which are available when the slider is set to Q Score 30 (>=Q30) and this is for each of the lanes for a run. For example the HiSeq machine has 2 lanes and the MiSeq machine only has a single lane. I have circled the information in the attached screenshot.

Please help me if there is a way to obtain the above data via Interop module in python? 

![SAV_QScore](https://user-images.githubusercontent.com/36762962/65037779-50ea9600-d946-11e9-9c4e-df2d584aed05.PNG)

**Comment by ezralanglois** [comment]
Filter by lane, just add the following:
`options.lane(1)`

`plot_qscore_histogram` does not produce a plot, it produces a data structure you can use to generate a plot.

Those numbers come out of the plot data structure populated by `plot_qscore_histogram`.

The boundary just splits the bar plot into two plots. So setting it to something large like 60, will give you everything in the first plot.

`bin = [data.at(0).at(j).x() for j in range(data.at(0).size())]`
`yield = [data.at(0).at(j).y() for j in range(data.at(0).size())]`

Then you just need to scale the yield appropriately.

yield = (total < 1000) ? total + (unitsInBillions ? "G" : "M") : (total / 1000) + (unitsInBillions ? "T" : "G");
