### ISSUE TITLE
Generate every metric from Run Summary Tab in SAV using python

### ISSUE THREAD

**Issue by jcs649** [Illumina/interop#200]
Hi,

I was wondering if it's possible to generate the same summary metrics from the run summary tab in SAV using this Python library. I was able to follow this tutorial so far (https://github.com/Illumina/interop/blob/master/docs/src/Tutorial_01_Intro.ipynb)
and view these metrics (error_rate, first_cycle_intensity, percent_aligned, percent_gt_q30, projected_yield_g, yield_g). However, I'm not certain how to access other metrics (Cluster PF%, Legacy Phasing/Prephasing, etc.) that were not covered in the tutorial. 
I read that the ```run_summary``` object should help but I'm not sure how to use this properly. Is there a function that can generate every metric seen on the SAV run summary tab? 

Thanks!

**Comment by nudpa** [comment]
@jcs649 , the tutorial above should provide that information. SAV only provides metrics like %PF and Legacy Phasing on the Read + Lane level. If you scroll down to the "Read 1 Summary" section, that describes the way to access these sorts of metrics: summary.at(read_index).at(lane_index)

Let us know if something's unclear or you can't find a metric with this.

**Comment by SSunkara** [comment]
Hello,
It wasn't very clear to me as well where exactly I could access the metrics that the OP was seeking.
This helped:
dir(py_interop_summary.lane_summary)

>>> print "\n".join([method for method in dir(py_interop_summary.lane_summary()) if not method.startswith('_') and method not in ("at", "this", "resize", "resize_stat", "size")])
cluster_count
cluster_count_pf
cycle_state
density
density_pf
error_rate
error_rate_100
error_rate_35
error_rate_50
error_rate_75
first_cycle_intensity
lane
percent_aligned
percent_gt_q30
percent_pf
phasing
phasing_offset
phasing_slope
prephasing
prephasing_offset
prephasing_slope
projected_yield_g
reads
reads_pf
tile_count
yield_g

**Comment by ezralanglois** [comment]
Closing this out
