### ISSUE TITLE
Indexing absolute values 

### ISSUE THREAD

**Issue by rafaloz** [Illumina/interop#202]
Hello Illumina, 

I want to get the absolute values for Reads identified (PF) from the Indexing tab in SAV. I am using the python bidding and I am having some issues:

When running the Indexing tutorial the '%Reads Identified (PF)" results are not exactly the same as the one I see in the SAV. I had two summary branches (summary.at(0) and summary.at(1)) in my data and I averaged the results from both branches to get the SAV number. ¿ Is that the way you are calculating it? 

Furthermore, I would like to use absolute values. When parsing with the app dumptext I get what I believe is the absolute number of reads of each index in the column clustercount. I have tried to find that data following the tutorial and parsing IndexMetricsOut.bin with:

`
index_metrics = run_metrics.index_metric_set()
index_metric = ndex_metrics.at(i)
`

and going over all its attributes. However, I can't find the result obtained by dumptext or the total number of reads identified for all indexes.

I am a pretty rookie bioinformatician, sorry if my questions seem trivial...
 
Thanks!

**Comment by nudpa** [comment]
Hello @rafaloz,

I'm not sure I follow your comment about there being two summary branches - are you referring to the blurb here https://github.com/Illumina/interop/blob/master/docs/src/Tutorial_04_Indexing_Metrics.ipynb, where summary is an instance of index_flowcell_summary? If so, then each .at() call should represent a lane (i.e. one of the dropdown options in the Indexing tab SAV). If you're trying to match the "All" lane view, it'd essentially be an average of the lane-level "% Reads Identified", weighted by the PF read count for that lane - in other words, (total reads demultiplexed across all lanes)/(total reads PF across all lanes).

The write_metric function here: https://github.com/Illumina/interop/blob/master/src/interop/model/metrics/index_metric.cpp#L421 is what dumptext is using to write out a single entry, so reproducing that should hopefully be as simple as copying this function.

**Comment by rafaloz** [comment]
Just nailed it, Thank you so much! 

One last question, for the NOVASEQ runs in the Analysis table in the flowcell chart only certain tiles have the measurement '% aligned'. Are those defined tiles to make the measurement? I mean, why the measurement appears only in those tiles and not on all the flow cell?

**Comment by nudpa** [comment]
Hello @rafaloz,

The short answer is that real-time alignment in RTA is quite expensive. On NovaSeq, there are a lot of tiles, so the memory footprint for robustly estimating alignment statistics on all tiles in RTA is large enough to not fit on the onboard computer. We chose to downsample tiles in RTA to get around this.

**Comment by rafaloz** [comment]
Thank you again!
