### ISSUE TITLE
clusters per read

### ISSUE THREAD

**Issue by rafaloz** [Illumina/interop#203]
Hello, 

I want to know the number of indexed clusters per read in a run. I am getting all the values from index metrics_out_bin as dumptext does and filtering per read. 

I expected a small variation between reads however, I get the same value for both reads. 

I checked:

The cluster count will not change from read to read. We expect the same value for this metric.

_Originally posted by @ezralanglois in https://github.com/Illumina/interop/issues/154#issuecomment-341924347_

I understand the values I got will be the same, but I do not understand why. Is there a reason behind it?

This is my code:
`

    run_metrics = py_interop_run_metrics.run_metrics()
    run_metrics.read(folder)

    index_metrics = run_metrics.index_metric_set()
    for i in range(index_metrics.size()):
        index_metric = index_metrics.at(i)
        for j in range(len(index_metric.indices())):
            lineaIndex = []
            lineaIndex.append(index_metric.lane())
            lineaIndex.append(index_metric.tile())
            lineaIndex.append(index_metric.read())
            lineaIndex.append((index_metric.indices()[j]).index1())
            lineaIndex.append((index_metric.indices()[j]).index2())
            lineaIndex.append((index_metric.indices()[j]).sample_id())
            lineaIndex.append((index_metric.indices()[j]).sample_proj())
            lineaIndex.append((index_metric.indices()[j]).cluster_count())
            listaIndex.append(lineaIndex)

    columnasIndex = ['Lane', 'Tile', 'read', 'Index1', 'Index2', 'Sample', 'Project', 'cluster_count']
    desglose_indexing = pd.DataFrame(listaIndex, columns=columnasIndex) # creates data dataframe

    desglose_indexing_reads = list(set(desglose_indexing.iloc[:, 2].values.tolist()))

    for read in desglose_indexing_reads:
        desglose_indexing_read = desglose_indexing[desglose_indexing['read'] == read] # filters per read
        clusters_read.append('Read num ' + str(read))
        clusters_read.append(desglose_indexing_read.iloc[:, 7].values.sum()) # sums clusters
        clusters_read_copy = clusters_read.copy()
        clusters_por_read.append(clusters_read_copy)
        clusters_read.clear()

`

**Comment by hutchinsonk** [comment]
Hi,

From my understanding I believe the counts are only done on the forward read and not reverse read. Every time I tried to capture both values I could only locate the one, most likely because they expect them to be the same so they don't do the calculation again.

**Comment by nudpa** [comment]
For a typical dual index run, a cluster is associated with a sample only if it matches both the index reads listed for the sample. Thus, the IndexMetrics record should be, by definition, independent of the read number (and to be honest, it's a little misleading that we write the read number as part of the record).

**Comment by rafaloz** [comment]
hmmmm okk!! thank you very much for your answers!
