### ISSUE TITLE
Estimating Sequence Coverage

### ISSUE THREAD

**Issue by hutchinsonk** [Illumina/interop#204]
Hi,

Based on reading the following [technote](https://www.illumina.com/documents/products/technotes/technote_coverage_calculation.pdf), I know the equation for determining the Sequence Coverage is C = LN/G.

• C stands for coverage
• G is the haploid genome length
• L is the read length
• N is the number of reads

I was wondering if there was a way to get all G, L, and N values from using the interop python classes?

As a last resort I am able to determine what G and L is based on previously entered data in our LIS but I had to determine what N was and I got that from the Cluster Count.

Can you confirm if the below is accurate for getting N and L values as well as how I could also get G?

**N =** 

```
run_metrics.read(runFolder)
summary = py_interop_summary.index_flowcell_summary()
py_interop_summary.summarize_index_metrics(run_metrics, summary)

summary.at(i).at(i).cluster_count()
```

**L =** (I am asking this because for a 600 cycle run this number ends up being 618 due to extra cycles. What number would be accurate in the calculation? 600 or 618 or another ie: 602?)

```
from interop import py_interop_run
run_info = py_interop_run.info()
run_info.read("RunFolder")
print("Number of cycles %d" % run_info.total_cycles()
```

**G = ?**

**Comment by nudpa** [comment]
@hutchinsonk , you can calculate L & N individually along the lines of what you have above, but assuming run-level statistics are acceptable, the number we report as "yield" in our summary (summary.nonindex_summary().yield_g()) is pretty much L*N in your equation (although note that the value above is scaled in units of gigabases).

Unfortunately, G comes from the reference genome you're using, which RTA has no knowledge of at the time of sequencing. This is thus not captured in any interop file.

**Comment by hutchinsonk** [comment]
@nudpa 

Thank you very much for the quick and accurate response.

So if I understand correctly, the yeild_g summary you describe is for the read on the entire run, but if I just wanted to calculate this for each individual sample so I can find out if some samples are below the defined threshold (say, 40x) to re-submit then I am able to do that with what I have outlined above.

**Comment by nudpa** [comment]
@hutchinsonk , if you want this to be per-sample, you'll have to use the output of demultiplexing (e.g. the index metrics) to give you the N from your equation. L can be calculated from the RunInfo - I'd define it as the number of useable cycles on all non-index reads.

Alternatively, if you have some sort of yield metric from bcl2fastq (or whatever you used to demultiplex), that's likely the N*L equivalent. This wouldn't be accessible from the InterOp library, though.

**Comment by hutchinsonk** [comment]
Thank you very much!
