### ISSUE TITLE
Add wheel for Python 3.8

### ISSUE THREAD

**Issue by mivade** [Illumina/interop#205]
There are currently no PyPI builds for Python 3.8. Could we please get these made?

**Comment by ezralanglois** [comment]
I think we are due for an update. I will put this out in a PR and close out some other issues along the way.

**Comment by ezralanglois** [comment]
Looks like I need to pay down some technical debt on the PR tests to ensure a new wheel is properly packaged and deployed. Once I get that done, we should have a Python 3.8 wheel out.
