### ISSUE TITLE
Errors in dumptext output for Nextseq data

### ISSUE THREAD

**Issue by ppswang** [Illumina/interop#206]
dumptext v1.1.8

Hi, 

The output generated by dumptext for NextSeq data have two sections that seem to be incorrectly formatted:

In `Image` section, the values rows actually have 8 columns, there appears to be an extra comma after the 4th column, creating an empty column
```
# Image,1
# Column Count: 7
# Channel Count: 2
Lane,Tile,Cycle,MinContrast_red,MinContrast_green,MaxContrast_red,MaxContrast_green
1,11301,1,,9178,9241,15109,14856
3,11401,1,,8879,8792,14321,14071
1,11101,1,,9118,10287,15133,16695
```

In `EmpiricalPhasing`, Column Count and the header line both say there are 5 columns, but in the values, there are only 4 columns. It seems like the data column for "Cycle" is missing

```
# EmpiricalPhasing,1
# Column Count: 5
Lane,Tile,Cycle,Phasing,Prephasing
3,11402,1.12304,2.50088
1,21101,1.49393,1.95321
1,21102,1.52629,1.83247
3,11502,1.7074,1.78394
```

**Comment by ezralanglois** [comment]
Thanks for pointing this out. I have a PR out to fix this. 
Before I can get that in, i need to pay down some technical debt to get the status checks working again.

**Comment by ppswang** [comment]
Thank you!
