### ISSUE TITLE
Error on Python, extraxcting information from run

### ISSUE THREAD

**Issue by nuin** [Illumina/interop#210]
Hi

I have a Python script that used the intro library to extract data from a run and insert into a DB. Pretty simple code, following the guidelines in the tutorial

```python
    metrics = {}
    run_metrics = py_interop_run_metrics.run_metrics()
    summary = py_interop_summary.run_summary()
    summary2 = py_interop_summary.index_flowcell_summary()

    py_interop_summary.summarize_run_metrics(run_metrics, summary)
    py_interop_summary.summarize_index_metrics(run_metrics, summary2)

    lane_summary = summary2.at(0)
```

Basically the initial commands run fine, until the last line, which is giving the following error all of a sudden:

```python
Traceback (most recent call last):
  File "run_metrics_interop_couch.py", line 134, in <module>
    extract_data(run_folder)
  File "run_metrics_interop_couch.py", line 47, in extract_data
    lane_summary = summary2.at(0)
  File "/Users/nuin/Envs/pipeline/lib/python3.7/site-packages/interop/py_interop_summary.py", line 952, in at
    return _py_interop_summary.index_flowcell_summary_at(self, n)
interop.py_interop_metrics.index_out_of_bounds_exception: Lane index exceeds lane count - 0 >= 0
/Users/travis/build/Illumina/interop/./interop/model/summary/index_flowcell_summary.h::operator[] (63)
```

Any idea of what might be wrong?

Thanks in advance

**Comment by ezralanglois** [comment]
`index_out_of_bounds_exception` is expected when you request the first object in an empty array
`summarize_index_metrics` will produce an empty summary if `IndexMetricsOut.bin` is not present.

**Comment by nuin** [comment]
Thanks, here is my InterOp folder

```
ls -alh InterOp                                                             
total 142240
drwxr-xr-x  12 nuin  staff   408B 28 Mar 02:16 .
drwxr-xr-x  16 nuin  staff   544B 28 Mar 09:35 ..
-rwx------   1 nuin  staff   4.2M 28 Mar 01:38 CorrectedIntMetricsOut.bin
-rwx------   1 nuin  staff   1.1M 28 Mar 01:38 EmpiricalPhasingMetricsOut.bin
-rwx------   1 nuin  staff   2.5M 28 Mar 01:38 ErrorMetricsOut.bin
-rwx------   1 nuin  staff    26M 28 Mar 01:38 EventMetricsOut.bin
-rwx------   1 nuin  staff   3.3M 28 Mar 01:38 ExtractionMetricsOut.bin
-rwx------   1 nuin  staff   810K 28 Mar 01:38 IndexMetricsOut.bin
-rwx------   1 nuin  staff   109K 28 Mar 01:38 PFGridMetricsOut.bin
-rwx------   1 nuin  staff    18M 28 Mar 01:38 QMetricsOut.bin
-rwx------   1 nuin  staff    13M 28 Mar 01:38 RegistrationMetricsOut.bin
-rwx------   1 nuin  staff    28K 28 Mar 01:38 TileMetricsOut.bin
```

I also tried with the MiSeqDemo folder from the Python notebooks

```python
python run_metrics_interop_couch.py ~/Downloads/MiSeqDemo                                  [ruby-2.6.3p62]
Traceback (most recent call last):
  File "run_metrics_interop_couch.py", line 131, in <module>
    extract_data(run_folder)
  File "run_metrics_interop_couch.py", line 47, in extract_data
    lane_summary = summary2.at(0)
  File "/Users/nuin/Envs/pipeline/lib/python3.7/site-packages/interop/py_interop_summary.py", line 958, in at
    return _py_interop_summary.index_flowcell_summary_at(self, n)
interop.py_interop_metrics.index_out_of_bounds_exception: Lane index exceeds lane count - 0 >= 0
/Users/travis/build/Illumina/interop/./interop/model/summary/index_flowcell_summary.h::operator[] (63)
```


Thanks

**Comment by nudpa** [comment]
Hello @nuin , can you confirm if you're loading the IndexMetrics in your run_metrics load call?

For instance, if you're followign this: https://github.com/Illumina/interop/blob/master/docs/src/Tutorial_01_Intro.ipynb, are you using a valid_to_load parameter to speed things up? If so, and you're using
>  py_interop_run_metrics.list_summary_metrics_to_load(valid_to_load)
to populate as that tutorial does, then that won't load IndexMetrics.

If that's it, then you'll either need a line that adds index_metrics to the list (as in: https://github.com/Illumina/interop/blob/master/docs/src/Tutorial_03_Low_Level.ipynb)
> valid_to_load[py_interop_run.Index]=1
or one that reloads just the InterOps involved with the indexing logic (as in: https://github.com/Illumina/interop/blob/master/docs/src/Tutorial_04_Indexing_Metrics.ipynb):
> py_interop_run_metrics.list_index_metrics_to_load(valid_to_load)

prior to calling a load/index summary

If this isn't it, let us know and we can debug further.

**Comment by nuin** [comment]
Yes, @nudpa I was missing one of the lines to load valid files, thanks a lot for the help and sorry to bother.
