### ISSUE TITLE
How to extract ErrorRate and BasePercent?

### ISSUE THREAD

**Issue by nicolazilio** [Illumina/interop#218]
Hi there,

I can't get `ErrorRate` or `BasePercent` data out of an InterOp metric files. I am, however, able to extract Q30Percent. For example:

```
from interop import py_interop_plot, py_interop_run_metrics, py_interop_run

run_folder = './run_qc'
run_metrics = py_interop_run_metrics.run_metrics()

valid_to_load = py_interop_run.uchar_vector(py_interop_run.MetricCount, 0)
valid_to_load[py_interop_run.Q]=1

run_metrics.read(run_folder, valid_to_load)

plot_data = py_interop_plot.candle_stick_plot_data()
options = py_interop_plot.filter_options(run_metrics.run_info().flowcell().naming_method())
py_interop_plot.plot_by_cycle(run_metrics, "Q30Percent", options, plot_data)
```

I thought it'd be as simple as changing `Q30Percent` in the code above to `ErrorRate` or `BasePercent`, but that doesn't work.  

Any suggestion is appreciated. Thank you in advance.

**Comment by nudpa** [comment]
Hello @nicolazilio,

I think the key is the line here:
valid_to_load[py_interop_run.Q]=1
which specifies the InterOp files to load.

For ErrorRate, you'd have to use: valid_to_load[py_interop_run.Error]=1
For BasePercent, you'd have to use: valid_to_load[py_interop_run.CorrectedInt]=1

Let me know if this still doesn't work

**Comment by ezralanglois** [comment]
Given it is difficult to know what metric lives where, you can also do the following:

```
valid_to_load = py_interop_run.uchar_vector(py_interop_run.MetricCount, 0)
py_interop_run_metrics.list_metrics_to_load_by_type(py_interop_run.Q30Percent, valid_to_load)
py_interop_run_metrics.list_metrics_to_load_by_type(py_interop_run.ErrorRate, valid_to_load)
run_metrics.read(run_folder, valid_to_load)
```

**Comment by nicolazilio** [comment]
@nudpa that worked, I can now access the error rate data. Thanks a lot! 

The next question that I now have is: how do I get to the `BasePercent` data. I guess this is probably not via the `candle_stick_plot_data` method I used above, but none of the names for the methods under `py_interop_plot` seem to point obviously to `BasePercent` data.

**Comment by nicolazilio** [comment]
I'm going to answer my own question. `candle_stick_plot_data` can also be used with `BasePercent`.
