### ISSUE TITLE
calcul strandard deviation

### ISSUE THREAD

**Issue by rglandie** [Illumina/interop#22]
I need to calcul standard deviation in many function. How to calcul standard deviation for  clusterDensity () , percent_aligned () etc .. ?

**Comment by ezralanglois** [comment]
Could you provide me with a little more information by answering the following questions:

1. Do you want this for C++ or C# or both?
2. Do you want all metrics or just a subset?

**Comment by rglandie** [comment]
This is for C++ and for these metrics: 
 -clusterDensity () 
-clusterCountPf ()
-percent_aligned (
-errorRate ()

**Comment by ezralanglois** [comment]
I will add some code to perform these simple statistics and some examples. I think the main thing you need to be aware of is NaN values. There are cases, such as % aligned, where no alignment was performed and this is indicated by a NaN. One such case is index sequences.

**Comment by ezralanglois** [comment]
I just merged https://github.com/Illumina/interop/pull/26 which should address this issue.

I added an example of how to use the new mean and variance algorithms here:
https://github.com/Illumina/interop/blob/master/src/examples/example4.cpp

I would note that when calculating the mean and/or variance of percent aligned, you should use the nan_ version. This will correctly excluded index reads where alignment was never performed.

**Comment by rglandie** [comment]
Thank you for help, 
I need to calculate the mean intensity for cycle 1 per lane  and the % read >= Q30 but i don't find functions to do this. Can you help me again ?

**Comment by ezralanglois** [comment]
I created a new issue for you https://github.com/Illumina/interop/issues/28

It helps us to track what is going on. I will answer there.

Best
