### ISSUE TITLE
Unable to read files

### ISSUE THREAD

**Issue by jacobcvt12** [Illumina/interop#220]
I have a directory "data" containing InterOp/, RunInfo.xml, and RunParameters.xml. When I try to read the metrics with 

```
from interop.py_interop_run_metrics import run_metrics
metrics = run_metrics()
metrics.read("data")
```

I get the following error

```
invalid_run_info_exception: Surface number exceeds number of surfaces in RunInfo.xml
for record 1_1413546001 in file IndexMetricsOut.bin - 1413546 > 2
/Users/travis/build/Illumina/interop/src/interop/model/run/info.cpp::validate (365)
```

Any idea what is causing this issue? Is there any way to get around it and read the files? I get a similar error when calling the `dumptext` utility, but the `summary` binary works fine on these files.

**Comment by nudpa** [comment]
@jacobcvt12 it looks like your IndexMetricsOut.bin file has been corrupted. If you're only looking for data that's not related to the contents of that file, using the read() call overload with a valid_to_load parameter, as, for instance, seen in blocks 15-17 here is recommended: https://github.com/Illumina/interop/blob/master/docs/src/Tutorial_05_Imaging_Table.ipynb.
