### ISSUE TITLE
Plotting %occupied / %pf on command line

### ISSUE THREAD

**Issue by sklages** [Illumina/interop#221]
Hi,
I wanted to generate plots like these, https://support.illumina.com/bulletins/2020/03/plotting---occupied-by---pass-filter-to-optimize-loading-concent.html from the command line.

Where do I get the data from?

a) I could directly read InterOp data (which one? Do you have a current format description of InterOp data files?)

b) I thought I could use use some tool from http://illumina.github.io/interop/apps.html but none of these seems to dump `%occupied` data.

Any hints, recommendations to get the data to generate these plots without using SAV?

Thanks,
Sven

**Comment by ezralanglois** [comment]
The plotting functionality show in the link is in SAV, not InterOp. The InterOp library provides the large table shown in the imaging tab.

The command line application that has this functionality is:
http://illumina.github.io/interop/imaging_table.html
It dumps a large table to disk. 

The files that are loaded for this table can by found with the following Python function:

```
from interop import py_interop_run
from interop import py_interop_table
valid_to_load = py_interop_run.uchar_vector(py_interop_run.MetricCount, 0)
py_interop_table.list_imaging_table_metrics_to_load(valid_to_load)
names = []
for i in range(py_interop_run.MetricCount):
  if valid_to_load[i] > 0:
    names.append(py_interop_run.to_string_metric_group(i))
print(names)
```

You can also load it in python with the following:

```
from interop import py_interop_run
from interop import py_interop_table
from interop import py_interop_run_metrics
import pandas as pd
import numpy as np

def print(run_folder):
    run_metrics = py_interop_run_metrics.run_metrics()
    run_metrics.read(run_folder, valid_to_load)
    columns = py_interop_table.imaging_column_vector()
    py_interop_table.create_imaging_table_columns(run_metrics, columns)
    row_offsets = py_interop_table.map_id_offset()
    py_interop_table.count_table_rows(run_metrics, row_offsets)
    column_count = py_interop_table.count_table_columns(columns)
    data = np.zeros((len(row_offsets), column_count), dtype=np.float32)
    py_interop_table.populate_imaging_table_data(run_metrics, columns, row_offsets,data.ravel())
    headers = []
    for i in range(columns.size()):
        column = columns[i]
        if column.has_children():
            headers.extend([str(column.name()) + " " + str(subname).strip() for subname in column.subcolumns()])
        else:
            headers.append(str(column.name()))
    df = pd.DataFrame(data, columns=headers)
    print(df)
```
You can use matplotlib or plotly to generate plots with the columns.

**Comment by sklages** [comment]
@ezralanglois thanks for the info! `imaging_table` is doing a perfect job! I somehow missed this tool.
That's what serves me best, downstream analysis is done in Perl ;-)
