### ISSUE TITLE
dumpText error on Novaseq S2 : Surface number exceeds number of surfaces

### ISSUE THREAD

**Issue by sybrohee** [Illumina/interop#222]
Dear all,

I used the dumptext binary (1.1.10) available on the website after bcl2fastq has been completed successfully on a S2 run.

```
# Version: v1.1.10
Surface number exceeds number of surfaces in RunInfo.xml for record 0_16777221 in file IndexMetricsOut.bin - 16777 > 2
/io/src/interop/model/run/info.cpp::validate (365)
```

Is there an issue on my side (corrupted file?) or is there a bug in dumptext? How can I check that?

On issue #220  , another user has a simiiar problem. 

Thank you for your help.

**Comment by nudpa** [comment]
@sybrohee, as you point out, this looks like a similar issue to #220 - the IndexMetrics file appears to be corrupted. This validation logic occurs during the file load itself, where by parsing records in the format described here: http://illumina.github.io/interop/binary_formats.html, it encounters a record labeled as lane 0, tile 16777221 (which doesn't make sense as the lanes are 1-indexed and the tiles are 4 digits).

**Comment by sybrohee** [comment]
Indeed, I will try to rerun blc2fastq, then.
