### ISSUE TITLE
which interop script parses BustardSummary.xml data

### ISSUE THREAD

**Issue by yelekley** [Illumina/interop#225]
Hello,
I need to obtain run statistics that are in BustardSummary.xml.  Could you please point me to a script that parses this information.

Thanks

**Comment by ezralanglois** [comment]
We don't support the GA with this library and state that fact in the Readme, see below:
![image](https://user-images.githubusercontent.com/2104878/90186986-ea484500-dd6d-11ea-992d-6233f9d78ffc.png)
