### ISSUE TITLE
How to get >=q30 cluster count per lane

### ISSUE THREAD

**Issue by yelekley** [Illumina/interop#226]
Hello,
Please suggest how to get >=q30 cluster count per lane.
Thank you

**Comment by ezralanglois** [comment]
Just checking, what sequencer is this for?

Also, InterOp support C++, Python and C#. What language do you want to get the metric using?

**Comment by yelekley** [comment]
Novaseq, Miseq and Nextseq. I prefer Python, Thanks

**Comment by yelekley** [comment]
Returning an error, no attributes 'mean'.
`fraction_gt_q30 = summary_lane.at(read_index).at(lane_index).percent_gt_q30().mean()/100`
AttributeError: 'float' object has no attribute 'mean'
thanks

**Comment by yelekley** [comment]
Another question if you don't mind...
When I calculate the total yield and the projected yield for the run. The numbers of the projected yield are very close to what's in BustardSummary under chip result summary. The sum of yield_g*1e9 is always less than what's in BustardSummary.
 So it's the projected yield that is in Bustard, and not the actual yield, do you know?
Thanks,
Here is the code:

```
tyield=0
pyield=0
for read_index in range(summary.size()):
	for lane_index in range(summary.lane_count()):
		yield_g = summary.at(read_index).at(lane_index).yield_g()
                 yieldtotal=yield_g*1e9
                 tyield += yieldtotal
                 yield_p = summary.at(read_index).at(lane_index).projected_yield_g()
                 projyield = yield_p*1e9
                 pyield += projyield
print(tyield)
print(pyield)
```

**Comment by nudpa** [comment]
@yelekley %Q30 is stored as the aggregate across all tiles in the lane directly (in other words, we already calculate a weighted average across tiles when you call .percent_gt_q30()), so it should work to just remove the .mean() from your expression above.

As far as yield vs. projected yield, yield represents the estimated amount of non-N bases that have been processed so far, while projected yield represents the expected amount of non-N bases by the end of the run. If a run is successfully completed, both should converge to the same value. If the run is still in progress, yield will be less than projected yield.
