### ISSUE TITLE
Unable to compile/link

### ISSUE THREAD

**Issue by sierra1bravo** [Illumina/interop#227]
Hi

Here's a newbie question. I've cloned the github repository to my hard disk, created a build directory, and ran the makefiles to install the interop library locally. Now I have two folders in my home folder, one containing the cloned github folder (called "interop") and another (called "build") that has the newly-created local installation files.

Which of these two folders would be considered the "install" folder that should be indicated in the g++ command line argument? I note that none of the example source files are available in the build folder...so, how do I compile a file, say example1.cpp?

Thanks in advance for any help...

s1b

**Comment by sierra1bravo** [comment]
Thanks very much...worked correctly this time.

The test folder MiSeqDemo is very useful for testing. Are there any other publicly accessible run folders available (just for testing purposes)?

Thanks again.

**Comment by nudpa** [comment]
@sierra1bravo there are plenty of public run folders on BaseSpace (in the "Demo Data" section here: https://basespace.illumina.com)

**Comment by sierra1bravo** [comment]
Thanks...much appreciated!
