### ISSUE TITLE
Metrics for command-line tool

### ISSUE THREAD

**Issue by pjonsson-ctx** [Illumina/interop#231]
The CLI (e.g. `plot_by_cycle`) takes a `--metric-name` argument where "Intensity" is the default. Are any other values available? If so, where is this described?

**Comment by nudpa** [comment]
Hello @pjonsson-ctx 

The full list of metrics can be found here: https://github.com/Illumina/interop/blob/master/interop/constants/enums.h#L41 . Specifically, the first field of each tuple represents a value for --metric-name. Specifically for plot_by_cycle, if the fourth field contains "CycleFeature", it should be a metric that varies by cycle that can be plotted here.

**Comment by pjonsson-ctx** [comment]
@nudpa Great, thanks!
