### ISSUE TITLE
We can no longer use this to get the instrument type.

### ISSUE THREAD

**Issue by thrichardson-twist** [Illumina/interop#232]
It simply returns 1024 for NextSeq1k2k and ISeq.  We have both instrument types and therefore cannot distinguish between the two programmatically as we can our other instruments.  Please fix this...

We're using python 3.8 and use it as follows:

    run_parameters = py_interop_run.parameters()
    run_parameters.read(run_folder)
    instrument_type = run_parameters.instrument_type()

**Comment by ezralanglois** [comment]
Thank you for pointing this out. I assume you are on the latest release.
I can see we lack unit tests around the RunParameters.xml for both NextSeq2k and iSeq, so I will add those while debugging this issue.

**Comment by ezralanglois** [comment]
This should be fixed now when the latest release is ready.
