### ISSUE TITLE
how to specify the location of IndexMetricsOut.bin if not in run/InterOp folder

### ISSUE THREAD

**Issue by yelekley** [Illumina/interop#237]
Hello,
How to specify the location of IndexMetricsOut.bin if it's store outside of the run folder?
Thanks

**Comment by ezralanglois** [comment]
There is no easy way to do this. The problem is that another application creates the IndexMetricsOut.bin and we cannot control where it goes.

The simplest solution that we use internally is to copy it into the InterOp folder after the fact.

**Comment by yelekley** [comment]
I can't write back to the original run folder dir.  What if I create a folder with run name and subdir InterOp in another location? Thanks

**Comment by ezralanglois** [comment]
You could do the following:

```
run = run_metrics()
run.read(run_folder())
run.read_metrics(index_run_folder, run.run_info().total_cycles(), 1)
run.finalize_after_load(run.count_legacy_bins()) # Always call this after read_metrics
```

You call `read` to load the original run folder, then you call `read_metrics` to add the additional index metrics. 
This is untested. A better way to do this would be to add a `concat` method to add additional metrics or a flag to `read`

**Comment by nudpa** [comment]
Another approach would be to copy the RunInfo.xml and whatever other InterOps you'd need (TileMetrics, at least) to your new folder and just read normally from there

**Comment by ezralanglois** [comment]
I like Nitin's suggestion better. I would do the RunParameters.xml too
