### ISSUE TITLE
sample ids absent from IndexMetricsOut.bin for NovaSeq S2/SP

### ISSUE THREAD

**Issue by yelekley** [Illumina/interop#238]
I ran InterOp code on NovaSeq, flowcell modes: S2 and SP and there are no sample names present in the index metrics output. Is there a workaround to get the sample names correlated with the barcodes, fraction_mapped and cluster_count metrics InterOp is pulling?
It's returning barcode_id with index_summary.at(sample).sample_id() for NovaSeq, however, the same function returns the library id for HiSeq. I need the library id for each barcode.

Thanks

**Comment by yelekley** [comment]
It's returning barcode_id with index_summary.at(sample).sample_id() for NovaSeq, however, the same function returns the library id for HiSeq.  I need the library id for each barcode. Thanks

**Comment by ezralanglois** [comment]
The `IndexMetricsOut.bin` should contain what was provided in the SampleSheet. Have you compared the sample sheets for both runs?

Also, was the same version/software used for BCL conversion?

**Comment by yelekley** [comment]
What happens if a barcode is accidentally swapped? Does InterOp output display the actual barcode used or what's on the sample sheet? Thanks

**Comment by ezralanglois** [comment]
Bclconvert or bcl2fastq will use what is in the SampleSheet to create the InterOp file.

**Comment by yelekley** [comment]
Thank you
