### ISSUE TITLE
How to calculate average_cycle_intensity

### ISSUE THREAD

**Issue by ArielZhen** [Illumina/interop#239]
Hi there,
I am having trouble figuring out how to use `corrected_intensity_metric` class from `py_interop_metrics`. [https://github.com/Illumina/interop/blob/73c3c2aa6f/interop/model/metrics/corrected_intensity_metric.h] No luck finding any examples or tutorials so far. I would like to get the value of `average_cycle_intensity` by doing something along the line of 
`from interop import py_interop_run_metrics, py_interop_run, py_interop_metrics`
`run_metrics = py_interop_run_metrics.run_metrics()` not sure if this is even needed
`valid_to_load = py_interop_run.uchar_vector(py_interop_run.MetricCount, 0)` again, not sure if this is even needed
`intensity_metric = py_interop_metrics.corrected_intensity_metric()`
`intensity_metric.average_cycle_intensity()` 
But not sure how to populate the `intensity_metric` object. 

I have also tried a different approach by doing 
`valid_to_load[py_interop_run.CorrectedInt]=1`
`intensity_metric = run_metrics.corrected_intensity_metric_set()` 
but that didn't populate the expected values to the `intensity_metric` object. 

Any help is appreciated. Thank you in advance.

**Comment by ezralanglois** [comment]
Hi Ariel,

First, you should be aware that `average_cycle_intensity` is not available on recent systems. 

https://github.com/Illumina/interop/blob/232e72a764b00265fdcaf93d58f47df4badfc427/interop/model/metrics/corrected_intensity_metric.h#L264

Here is a simple example loading the metric

```
# run_folder is a variable that contains the file path to some run folder
import interop.py_interop_run_metrics as interop_metrics
metrics = interop_metrics.run_metrics()
metrics.read(run_folder)
corrected_intensity_metric_set = metrics.corrected_intensity_metric_set()
data = []
for i in range(corrected_intensity_metric_set.size()):
    data.append([corrected_intensity_metric_set.at(i).lane()
                 , corrected_intensity_metric_set.at(i).tile()
                 , corrected_intensity_metric_set.at(i).cycle()
                 , corrected_intensity_metric_set.at(i).average_cycle_intensity()
                ])
print(data)
```

**Comment by ArielZhen** [comment]
Yes, seems like `average_cycle_intensity` is not available for our system since I am getting all 0s for `corrected_intensity_metric_set.at(i).average_cycle_intensity()`. Is there an alternative to get the same metric?

**Comment by ezralanglois** [comment]
`extraction_metric_set.at(i).max_intensity(0)`
0 is the index of the channel in the RunInfo; so if green is first, then green is `0`.

**Comment by ArielZhen** [comment]
Got it! Does something like this 
```run_metrics = py_interop_run_metrics.run_metrics()
valid_to_load = py_interop_run.uchar_vector(py_interop_run.MetricCount, 0)
valid_to_load[py_interop_run.Extraction]=1
run_metrics.read(run_folder, valid_to_load)
extraction_metrics = run_metrics.extraction_metric_set()
data = []
for i in range(extraction_metrics.size()):
    for j in range(extraction_metrics.channel_count()):
        data.append(extraction_metrics.at(i).max_intensity(j))```
looks right?

**Comment by ezralanglois** [comment]
The code should work. The result would be the average P95 over all cycles and tiles.
This will not give the same value as the average intensity over the tile.

**Comment by ArielZhen** [comment]
Thank you very much!
