### ISSUE TITLE
Plot q-score histogram of "values" instead of "low ends" 

### ISSUE THREAD

**Issue by BrettHoutz** [Illumina/interop#240]
My application uses interop Python binding to generate a q-score histogram. When testing with a run using Q-Metrics format version 5.

```py
qscore_data = py_interop_plot.bar_plot_data()
options = py_interop_plot.filter_options(run_metrics.run_info().flowcell().naming_method())
py_interop_plot.plot_qscore_histogram(run_metrics, options, qscore_data, 60)
qscore = [qscore_data.at(0).at(j).x() for j in xrange(qscore_data.at(0).size())]
print(qscore)
# prints [10.0, 20.0, 25.0, 30.0, 35.0]
```

The values in the `qscore` list are the "low ends" described in [the format documentation](http://illumina.github.io/interop/q_v5.html). I confirmed this by inspecting a hexdump of `QMetricsOut.bin`.

```
0000000 05 ce 01 07 02 0a 14 19 1e 23 28 09 13 18 1d 22
0000010 27 28 02 0e 15 1b 20 24 28 03 00 89 2c 01 00 00
0000020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
```

The bytes `02 0a 14 19 1e 23 28` represent the values 2, 10, 20, 25, 30, 35, and 40.

Instead of the low ends, i would like to retrieve the "values" described in the documentation. In the bin data above that would be 2, 14, 21, 27, 32, 36, and 40. This is for backwards compatibility with display software built for older binary formats.

Is it possible to do this using InterOp?

**Comment by ezralanglois** [comment]
So, to get the values you need, you can view them as follows:

```
q_metric_set = run_metrics.q_metric_set()
bins = q_metric_set.bins()
print([(bins[i].lower(), bins[i].value(), bins[i].upper()) for i in range(bins.size())])
```

You can update the plot object (if that is your goal) as follows:
```
hist_plot_index = 0
for i in range(qscore_data.at(hist_plot_index).size()):
    point = qscore_data.at(hist_plot_index).at(i)
    qscore_data.at(hist_plot_index).at(i).set(bins[i].value(), point.y(), point.width())
```

And view the result as you did above:
```
qscore = [qscore_data.at(0).at(j).x() for j in range(qscore_data.at(0).size())]
print(qscore)
```

**Comment by BrettHoutz** [comment]
That works! Thank you for the quick response.
