### ISSUE TITLE
how to get %  >=q30, % PhiX aligned and % demultiplexed at library level

### ISSUE THREAD

**Issue by yelekley** [Illumina/interop#253]
Hello,
I would like to get %  >=q30, % PhiX aligned and % demultiplexed at  library level.  I'm able to get these stats at 'lane' and 'read' level but wondering how to get these at library level.

I need to get % of >= Q30 Bases (PF) and %PhiX aligned per sample_id for QA monitoring.  % of >= Q30 is listed in Demultiplex_Stats.htm, however, it would be nice to avoid parsing the file and just use an InterOp library.  Could you please let me know if it's possible or not? If not possible, I will parse the htm file.

Thanks

**Comment by ezralanglois** [comment]
The InterOp library does provide this functionality. You cannot get % PhiX aligned per sample because PhiX is not indexed.
We don't have % >=Q30 per sample either. You can use FastQC to get that information.
% Demux can be obtained from the output of the bcl conversion program.
