### ISSUE TITLE
Cycles per reads including index cycles - python

### ISSUE THREAD

**Issue by iab-bioinformatics** [Illumina/interop#254]
I am try to return the value about the number of cycles no the total one but the one per read and per index (251 | 6 | 251). I could not find the attribute I need to use to come to this value. 

Thanks for the answer in advance!

**Comment by ezralanglois** [comment]
Do you need the total? Also, I can provide an example later.

In short, after you call `read` in `run_metrics` you can then call `run_info` which has reads. Reads contains the info you need for each read.

**Comment by ezralanglois** [comment]
```
from interop import py_interop_run_metrics, py_interop_run
run_metrics = py_interop_run_metrics.run_metrics()
valid_to_load = py_interop_run.uchar_vector(py_interop_run.MetricCount, 0)
valid_to_load[py_interop_run.Error]=1
run_metrics.read(run_folder, valid_to_load)
run_info = run_metrics.run_info()
reads = run_info.reads()
[{'Number': reads[r].number(), 'IsIndex': reads[r].is_index(), 'IsReverseComplement': reads[r].is_reverse_complement(), 'TotalCycles': reads[r].total_cycles()} for r in range(reads.size())]


```
