### ISSUE TITLE
Q: More complete documentation on Python(3) bindings?

### ISSUE THREAD

**Issue by sklages** [Illumina/interop#259]
Just wondering if you have some  more complete documentation giving some more explanations on the methods available and used in each "Module"? 

.... the docs are just showing some examples on how to get some data from InterOp. 

Currently it is faster and more convenient for me to parse the various output `csv/xml` files created by `bcl2fastq` or `bcl-convert`.

**Comment by ezralanglois** [comment]
Ya, this has been in our backlog for a while. What we have been slowly working on are more intuitive methods for accessing the data. 

For example, there will be a new module that ties together the various `io` to make reading in the metrics easier, with proper doc strings and examples in the doc string that double as unit tests to ensure the examples don't go out of date.

Another example would be generating the imaging table. We have a single function to wrap this that we use internally. 

We do plan to release these simplified functions in the future, but I don't have a timeline yet.

Ideally, we would provide a set of 5-10 Python functions that cover most use cases that are bullet proof and rely on only `numpy` and `pandas`.

**Comment by sklages** [comment]
Sounds great :-)  thanks for the information.

**Comment by sklages** [comment]
It is (for me) not obvious what has been changed in the python binding and where (version 1.1.22)?
Using `pip install interop` on Manjaro Linux still lists `1.1.21` as current version.

What am I missing?

**Comment by ezralanglois** [comment]
Looks like it failed to deploy. Unfortunately, this is not something we test in the PR. I will look into it.

**Comment by ezralanglois** [comment]
I just retagged it, should trigger the builds again. I don't see anything obvious as to why it failed.

**Comment by ezralanglois** [comment]
Looks like it deployed for Linux
http://illumina.github.io/interop/python_binding.html
See `New simplified interface`

**Comment by sklages** [comment]
```
Installing collected packages: interop
  Attempting uninstall: interop
    Found existing installation: interop 1.1.21
    Uninstalling interop-1.1.21:
      Successfully uninstalled interop-1.1.21
Successfully installed interop-1.1.22
```
Now it works fine. The `New simplified interface` looks promising :+1:  thanks a lot.
