### ISSUE TITLE
Usage example of dumptext

### ISSUE THREAD

**Issue by CloeP** [Illumina/interop#260]
I am trying to use _dumptext_ to convert the binary InterOp files (e.g, QMetricsOut.bin & QMetricsByLaneOut.bin) to .csv formatted documents.

I was successfully able to install "InterOp-1.1.21-Darwin-AppleClang" and dumptext works as an executable.

However, I am not sure what type of file it can take as an input. Additional information is that I was able to download a specified run using the base-space CLI.

When I navigate into the /Run/InterOp folder and run: dumptext QMetricsOut.bin, I get the following error: 
Version: v1.1.21
cannot open file QMetricsOut.bin/RunInfo.xml
/Users/travis/build/Illumina/interop/src/interop/model/run/info.cpp::read_file (300)

I am not Travis and I didn't make a build folder. This suggests that either I didn't actually build/configure dumptext correctly or I am misusing the syntax.

Any suggestions would be extremely helpful. Thanks in advance.
I am working on a Mac OS Big Sur with zsh.

**Comment by ezralanglois** [comment]
http://illumina.github.io/interop/dumptext.html

It is run like so
```
dumptext 140131_1287_0851_A01n401drr
```

where `140131_1287_0851_A01n401drr` is a folder that contains at least a `RunInfo.xml` and `InterOp` subdirectory.
