### ISSUE TITLE
Extract metrics by cycle with python

### ISSUE THREAD

**Issue by rpwang** [Illumina/interop#265]
Hi, 

I was wondering if it was possible to get  some metrics out by each cycle using Python? I would like to extract datapoints similar from plot_by_cycle script. 

Thanks 
rp

**Comment by sklages** [comment]
Well, you can use the new "[simpified python interface](http://illumina.github.io/interop/namespacecore.html)"  to read the imaging table ..

```python
import interop as iop

run_metrics = iop.read(run_folder)

def read_imaging_table(run_metrics):
    ar = iop.imaging(run_metrics)
    df = pd.DataFrame(ar)

    # some values should be integers
    change_data_type = {
        'Lane'             : int,
        'Tile'             : int,
        'Tile Number'      : int,
        'Read'             : int,
        'Cycle'            : int,
        'Cycle Within Read': int,
        'Swath'            : int,
        'Surface'          : int
    }

    return df.astype(change_data_type)
```

and then plot the data accordingly. See http://illumina.github.io/interop/namespacecore.html#ab181cd004c7d8d415c5fb0b5a50f3dac

**Comment by rpwang** [comment]
Hi sklages,

This is what I need and thanks for the links to the docs!
