### ISSUE TITLE
Q: Q>=30 fraction per barcode (== library) per lane

### ISSUE THREAD

**Issue by sklages** [Illumina/interop#266]
Currently I am compiling quite a lot of stats for some "demultiplexing / run report" (mainly) using the Python bindings ..
However, I didn't find a way to get the `%Q>=30 fraction` per **barcode** (and per lane) ... 

Any idea how to do this. I want to avoid to read files other than the run XMLs and InterOp ... (currently this could be deduced from `Stats.json` AFAICS) ..

**Comment by ezralanglois** [comment]
This is not currently apart of InterOp. Adding it has been under discussion recently, but I would next expect that to change any time in the next year.

**Comment by sklages** [comment]
oh, okay, that would be quite useful, as it may directly show issues with libraries "early" on demultiplexing level before running and evaluating any QC on the final fastq files .. so thumbs up for this one :+1:

**Comment by sklages** [comment]
@ezralanglois .. just to get you correctly: is that not part of the InterOp file specifications or is it just not part of the programming API / Python bindings?

`Stats.json` reports `Yield` and `YieldQ30` for each sample/barcode. Where has this been deduced from?

**Comment by ezralanglois** [comment]
It is not apart of the InterOp file specification. There is some discussion about whether this should be supported by InterOp given that every other metric comes from RTA, whereas this come from bclconvert/bcl2fastq

**Comment by sklages** [comment]
I guess this is the same for the "undetermined indices" metrics (seqs, counts)? Coming from bcl-convert/bcl2fastq and written to some textual output files (Top_Unknown_Barcodes.csv/Stats.json)..?

**Comment by ezralanglois** [comment]
Yup, same for that.

**Comment by ezralanglois** [comment]
No plan to support this in InterOp. I believe bclconvert will deprecate writing out the InterOp file
