### ISSUE TITLE
Can this be run on the Nextseq 2000 directly?

### ISSUE THREAD

**Issue by SharifShaaban-PHS** [Illumina/interop#275]
Can this be installed and run directly on the Nextseq 2000 while the data is being written to a network location?

**Comment by ezralanglois** [comment]
Yes. The binaries are built on an CentOS 5 image and should work on most Linux distributions.

**Comment by SharifShaaban-PHS** [comment]
Hi Robert,

Thanks for your answer. Does this mean that Interop could be run on the NextSeq 2000 whilst the sequencing run is happening? I was under the impression that the CentOS backend of the machine was locked/restricted while runs were ongoing.

Cheers


________________________________

**Comment by ezralanglois** [comment]
I can only comment from the perspective of the InterOp software here. You would need to talk to a field service engineer about whether it works from a sequencer perspective given the restrictions you mentioned.

I imagine those restrictions are in place so you don't inadvertently cause a sequencing run to fail.
