### ISSUE TITLE
calling `interop_summary` and `interop_index-summary` when using bcl-convert

### ISSUE THREAD

**Issue by BCArg** [Illumina/interop#278]
I am switching from bcl2fastq to bcl-convert. In order to get and store run metrics I run `interop_summary` and `interop_index-summary` (both installed with [conda](https://anaconda.org/bioconda/illumina-interop)) in the run directory where the following is present:

1. `RunInfo.xml`
2. a folder named `InterOp` - generated by `bcl2fastq`

`bcl-convert` does not generate the `InterOp` folder, as far as I can tell, and according to [this documentation](https://emea.support.illumina.com/bulletins/2020/10/upgrading-from-bcl2fastq-to-bcl-convert.html), this is not possible.

Is it possible to use `interop_summary` and  `interop_index-summary` on the files generated by `bcl-convert`? If not, is there an equivalent program that can be used?

**Comment by BCArg** [comment]
IndexMetricsOut.bin and RunInfo.xml are fine, they are generated by `bcl-convert`. The content of the `Reports` folder is shown below:

```
-rw-rw-r-- 1 ngs ngs   14312  9. Nov 12:21 Adapter_Metrics.csv
-rw-rw-r-- 1 ngs ngs   15882  9. Nov 12:21 Demultiplex_Stats.csv
-rw-rw-r-- 1 ngs ngs   49110  9. Nov 12:00 fastq_list.csv
-rw-rw-r-- 1 ngs ngs      35  9. Nov 12:21 Index_Hopping_Counts.csv
-rw-rw-r-- 1 ngs ngs 7883617  9. Nov 12:21 IndexMetricsOut.bin
-rw-rw-r-- 1 ngs ngs   16423  9. Nov 12:00 RunInfo.xml
-rw-rw-r-- 1 ngs ngs    6330  9. Nov 12:00 SampleSheet.csv
-rw-rw-r-- 1 ngs ngs    5422  9. Nov 12:21 Top_Unknown_Barcodes.csv
```

It appears that `TileMetricsOut.bin` is also required, is it possible to generate this file with `bcl-convert`?

**Comment by ezralanglois** [comment]
Yes, TileMetricsOut.bin is required. It is in the run folder and is not produced by bcl-convert
