### ISSUE TITLE
Documentation...?

### ISSUE THREAD

**Issue by oakeley** [Illumina/interop#285]
Please can you provide some basic documentation for how to use these libraries?
For example: 
1. a list of available functions
2. Examples of how to call
3. Perhaps an example script to make some kind of useful QC report from the interop data to PDF

**Comment by ezralanglois** [comment]
A link to the documentation is in the upper left, see below
<img width="344" alt="image" src="https://user-images.githubusercontent.com/2104878/171971332-64a941ec-5ab3-40be-a79c-96603c391596.png">

This is a good starting point:
http://illumina.github.io/interop/modules.html

Only the C++ interface is documented, but the Python and C# is largely the same.

Here are some examples:

http://illumina.github.io/interop/examples.html

Sorry, I don't know much about generaring PDF reports.
