### ISSUE TITLE
Calculate the % read >= Q30

### ISSUE THREAD

**Issue by ezralanglois** [Illumina/interop#29]
How to Calculate the % read >= Q30

Referenced from: https://github.com/Illumina/interop/issues/22
@rglandie

**Comment by ezralanglois** [comment]
I put this in out backlog, not sure when I will get to it.

**Comment by rglandie** [comment]
When you said "This is additional functionality we plan to offer in the future" in  Calculate Mean intensity for cycle 1 per lane #28 , you talk about RunInfo parsing ? You need to develop this functionnality to get % read >=Q30 ? This mean for now you can't calculate this metric ?

**Comment by ezralanglois** [comment]
For the immediate future, we plan to provide all the summary statistics you would find in SAV. This will be done in a data structure that provides that metrics for overall, by read and by lane per read. To do this, we first need to provide the ability to parse the run info.

The two metrics you asked for both depend on information that is only available in the RunInfo.xml. For example, first cycle intensity only reports the A channel or the Red channel. The order of the channels can only be extracted from the RunInfo. The example I provided will only consistently match SAV if you set up your own run info parser and extract the channel order and select the index of either the A channel or the Red channel.

Also, if you want %Q30 by read, then you need to know what a read is. This information is also only available in the RunInfo.xml.

The percent greater than Q30 is a little more complicated. You can try to do both of these yourself, but I wanted you to be aware that we do plan to do something more comprehensive in the future. I don't have a hard time line for this right now.

**Comment by rglandie** [comment]
Hi Rob, 

i want to use two functions in interop in quality metric module and i can't use them. 

total_over_qscore_cumulative and total_over_qscore. In this function it exist 2 arguments:

-qscore	percentage of clusters over the given q-score value
-bins	q-score histogram bins

i don't understand exactly what's these arguments. Can you give me an example ? 

Thanks,

**Comment by ezralanglois** [comment]
The calculation requires the q-score bins, which are in the header (shared among all q-metrics). The header is apart of the metric set.

So to calculate the total >= Q30 for an arbitrary tile/cycle, you can do the following:

 q_metrics q_metric_set;
 read_interop(argv[1], q_metric_set);
 q_metric& metric0 = q_metric_set.at(0);
std::cout << "Total >= Q30: " << metric0.total_over_qscore(30, q_metric_set.bins()) << std::endl;

**Comment by rglandie** [comment]
What does the number in q_metric_set.at (0) ? It's the tile, cycle number or other thing ?

**Comment by rglandie** [comment]
Ideally i want to calculate this metric by lane, but if isn't possible i would calculate this metric by cycle or by tile.

**Comment by ezralanglois** [comment]
q_metric_set is of type q_metrics, which is a collection of q_metric's. Each q_metric holds an identifier, lane, tile, cycle as well as the q-value histogram.

The master branch of the code has the SAV summary tab model in it:
e.g. https://github.com/Illumina/interop/blob/master/interop/model/summary/lane_summary.h

I am working on adding the logic to calculate all those values right now and it should go in shortly.

**Comment by rglandie** [comment]
i understand that exist an identifier lane an identifier cycle, an identifier cycle etc..
But i don't understand what's the number in q_metric_set.at (0). what's at () ? what 0  is? 
I want and i need to have the number %>=q30 which is present in run summary in SAV software

**Comment by ezralanglois** [comment]
Maybe it is easier to think of it this way, consider you have a collection of ints. You can represent that collection as an std::vector<int>. Now, you want to access the first int, you can do the following:
std::vector<int> vec(3, 3);
int current_int = vec.at(0);

In the above case, q_metrics is a collection of q_metric objects. Each q_metric object can be accessed the same way:
q_metric_set.at(0) gives you the first q_metric.

If you want to know what lane it belongs to, then you would just say:
q_metric_set.at(0).lane(). So you can use that member function to sum up a specific metric by lane.

**Comment by amacbride** [comment]
Hello, I had been using the local histogram versions of these calls with no problems.  I'd like to test out the cumulative versions, but is_cumulative_empty() is always returning false. Is there some other initialization that needs to be done to get the cumulative statistics (in particular, total_over_qscore_cumulative() and percent_over_qscore_cumulative)?

**Comment by ezralanglois** [comment]
If you load the q-metrics from run metrics, then it should be created.

I am guessing that you are not, if you are doing this at a lower level, then you need to call `populate_cumulative_distribution` on the q-metric set.

**Comment by ezralanglois** [comment]
Please create a new ticket, rather than using a closed one. It is easy to me to forget about a question when it is on a closed ticked.

**Comment by ezralanglois** [comment]
Locking this thread.
