### ISSUE TITLE
Recent InterOp Python Wheels do not run on Mac OS X High Sierra 10.13

### ISSUE THREAD

**Issue by lukato01** [Illumina/interop#293]
Please advice on how to fix this error that i encountered while running command : 
`python3.8 -m interop --test`

File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.8/site-packages/interop/__init__.py", line 11, in <module>
    from interop.core import *
  File "/usr/local/lib/python3.8/site-packages/interop/core.py", line 55, in <module>
    import interop.py_interop_run_metrics as interop_metrics
  File "/usr/local/lib/python3.8/site-packages/interop/py_interop_run_metrics.py", line 13, in <module>
    from . import _py_interop_run_metrics
ImportError: dlopen(/usr/local/lib/python3.8/site-packages/interop/_py_interop_run_metrics.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /usr/local/lib/python3.8/site-packages/interop/_py_interop_run_metrics.so (which was built for Mac OS X 11.6)
  Expected in: /usr/lib/libSystem.B.dylib
 in /usr/local/lib/python3.8/site-packages/interop/_py_interop_run_metrics.so

**Comment by ezralanglois** [comment]
Are you running the new M1 Mac OSX?

If so, there is no automated build for that yet. You can see this issue:
https://github.com/Illumina/interop/issues/282

Basically, you need to build it yourself.

**Comment by ezralanglois** [comment]
@lukato01 If you have a chance, can you check whether these new artifacts work? I don't have that version of OS X to test whether this worked.

https://github.com/Illumina/interop/suites/7407782942/artifacts/302085019

This will give a zip file with all the wheels, so you can select the python version you want to install.

**Comment by lukato01** [comment]
i tested it and artifact interop-1.1.25.dev2-cp39-cp39-macosx_10_9_x86_64.macosx_10_9_intel.macosx_10_10_intel.macosx_10_10_x86_64.whl works.

**Comment by ezralanglois** [comment]
> i tested it and artifact interop-1.1.25.dev2-cp39-cp39-macosx_10_9_x86_64.macosx_10_9_intel.macosx_10_10_intel.macosx_10_10_x86_64.whl works.

Thanks for testing this, I appreciate it.

**Comment by lukato01** [comment]
here are the files that are in the run folder which were downloaded from the Illumina BaseSpace
`User:Desktop$ ls kit_basespace_v2_eq_a/*

kit_basespace_v2_eq_a/RunInfo.xml

kit_basespace_v2_eq_a/InterOp:
CorrectedIntMetricsOut.bin	ExtractionMetricsOut.bin	QMetricsByLaneOut (1).bin	TileMetricsOut.bin
ErrorMetricsOut.bin		QMetrics2030Out.bin		QMetricsOut.bin 
`

**Comment by ezralanglois** [comment]
Prior to this line add `per_lane_summary = pd.DataFrame(summary(run_folder, 'Lane'))`

```
print(run_folder)
print(type(run_folder))
per_lane_summary = pd.DataFrame(summary(run_folder, 'Lane'))
```

The problem is likely the type of `run_folder`
