### ISSUE TITLE
no result was returned

### ISSUE THREAD

**Issue by daisyflemming** [Illumina/interop#295]
Hello,

I am using Centos Linux v7. I downloaded the compressed folder for Linux and ran ./index-summary but I didn't get any result or errors

![image](https://user-images.githubusercontent.com/6922340/179615602-88c74189-553f-41cf-871b-7b0b222e4f35.png)

I checked that  my run directory has RunInfo.xml and runParameters.xml
InterOp/ has TileMetricsOut.bin

Any advice? Thanks

**Comment by ezralanglois** [comment]
Does it have `<run_folder>/InterOp/IndexMetricsOut.bin`?

**Comment by daisyflemming** [comment]
No, it doesn't. We have these only
<run_folder>/InterOp/ControlMetricsOut.bin
<run_folder>/InterOp/CorrectedIntMetricsOut.bin
<run_folder>/InterOp/ErrorMetricsOut.bin
<run_folder>/InterOp/ExtractionMetricsOut.bin
<run_folder>/InterOp/TileMetricsOut.bin

**Comment by ezralanglois** [comment]
This program requires both Index and Tile metrics. It should probably report an error that Index is missing, but it does not.

**Comment by daisyflemming** [comment]
Thanks I will check with illumina tech support how to generate IndexMetricsOut.bin.
BTW, do you have an older module that does not require IndexMetricsOut.bin?

**Comment by ezralanglois** [comment]
No, that file contains all the important for the index summary.
