### ISSUE TITLE
Way to get all indexes from python 

### ISSUE THREAD

**Issue by hotsoupisgood** [Illumina/interop#305]
Hi, I would like to get all the determined and undetermined indexes using the python library but I am not seeing a way to do this. Is there something that I might be missing?

**Comment by ezralanglois** [comment]
I am not sure what you want. Just the number of determined and undetermined?

If so, then you can use this function from interop.core:
https://github.com/Illumina/interop/blob/3178e084f6385fd6e3bfc82e8b121531929cdcad/src/ext/python/core.py#L500

**Comment by hotsoupisgood** [comment]
I think that function contains what I am looking for. I think converting to the indexing table is what I am looking for to get the list of barcodes.

**Comment by hotsoupisgood** [comment]
Hey, still having some trouble finding unknown barcodes. What I am looking for is similar to the Stats.json that gets generated in the bcl2fastq. But Just the unknown barcodes part.

**Comment by ezralanglois** [comment]
I missed that part. InterOp only includes known bar codes. bcl2fastq and bclconvert should produce a text file called `top unknown barcodes` (not the exact name).

**Comment by hotsoupisgood** [comment]
Ok, thanks!
