### ISSUE TITLE
interop_summary command issue

### ISSUE THREAD

**Issue by mcnairr2** [Illumina/interop#306]
Having issue creating an interop summary file for a NextSeq run  where the control software is v1.5 and the DRAGEN software is v3.10.

(base) -bash-4.2$ cd /data/SBI_Illumina_GA2_runs/NextSeq/230117_VL00138_100_AACHVV5M5/
(base) -bash-4.2$ interop_summary --csv=1 . > 230117NextSeq-interop_summary.csv
No format found to parse ErrorMetricsOut.bin with version: 6 of 3
/opt/conda/conda-bld/illumina-interop_1618932334259/work/./interop/io/metric_stream.h::read_metrics (109)

**Comment by ezralanglois** [comment]
It looks like the latest version of InterOp should work. 
1. What version are you using?
2. Assuming it is not 1.2.0, have you tried to upgrade to 1.2.0?

**Comment by mcnairr2** [comment]
It looks like we are using v1.1.23.  We have not tried to upgrade to v1.2.0, is it as simple as going in Linux and running the conda install?  Would I need root access to run the install?

**Comment by ezralanglois** [comment]
I am not sure how you originally installed it. If it is available on conda, then someone else is packaging it there. 

I cannot comment on whether you would need root either. That is a local system issue.
