### ISSUE TITLE
Python question: Reading RunParameters.xml

### ISSUE THREAD

**Issue by kohleman** [Illumina/interop#309]
Hi,
I would like to read some values from RunParameters.xml. Instead of parsing the XML file by myself I would rather prefer to use InterOP. Could you point me to the documentation, give me a simple example or even a gist?

**Comment by ezralanglois** [comment]
Hi,
InterOp does not parse the full RunParameters.xml. It is only parsed to get the `instrument_type`
https://github.com/Illumina/interop/blob/master/interop/model/run/parameters.h
