### ISSUE TITLE
v1.1.27 and higher dumptext is not backwards compatible with error metrics < v6

### ISSUE THREAD

**Issue by channsoden** [Illumina/interop#314]
I'm guessing a bit on the issue title, and this issue affects interop_dumptext.

v1.1.27 and higher only work for parsing runs from our NextSeq 2000, and attempting to parse runs from our other instruments results in a core dump. V1.1.25 and lower works for runs from our other instruments, but attempting to parse runs from the NextSeq 2000 gives the following error when starting to parse the error metrics:
```
No format found to parse ErrorMetricsOut.bin with version: 6 of 3
/opt/conda/conda-bld/illumina-interop_1659474011889/work/./interop/io/metric_stream.h::read_metrics (109)
```

I'm guessing that the update on the NextSeq 2000 to accommodate 600 cycle runs caused it to output v6 error metrics, support for which was then added in v1.1.27, but that caused an error when trying to parse the error metrics from machines that still output v3 error metrics.

**Comment by ezralanglois** [comment]
Yes, interop is kept backwards compatible. Upgrading is always safe and you get the latest features.
