### ISSUE TITLE
Nextseq 500 no values for read.error_rate().mean() and read.percent_aligned().mean()

### ISSUE THREAD

**Issue by yelekley** [Illumina/interop#316]
Hello,
I'm not getting any values per read with read.error_rate().mean() and read.percent_aligned().mean() for Nextseq 500 but works fine with Novaseq output that we also use. Do you have any suggestions how to extract these metrics? Thanks

**Comment by ezralanglois** [comment]
Is this for every NextSeq 500 run? Or just one run? 

If there is no PhiX spiked or if the spike is very small, then those values should be NaN
