### ISSUE TITLE
Index with # of reads information

### ISSUE THREAD

**Issue by Nitin123-4** [Illumina/interop#325]
Hi team,

I am using this tool for the first time. From the example MiSeq run or from any Novaseq run, I want the list of indexes sequenced with total reads. 

For Example: ATGCATCG+GCTAGCAG : 4576234
Can you please help me to get the python code for it?

Thanks.

**Comment by ezralanglois** [comment]
I think you are looking for this
https://github.com/Illumina/interop/blob/master/docs/src/Tutorial_04_Indexing_Metrics.ipynb

Be aware that the IndexMetricsOut.bin is not produced by RTA. It is produced by the bcl conversion software. On some systems, it needs to be moved into the InterOp directory manually if it is not already there.

**Comment by Nitin123-4** [comment]
Thanks for your response. I ran it and see that it gives all the indexes which are there in SampleSheet.csv.

Is it possible to get the Index 1 (I7),Index 2 (I5) ,% Reads Identified (PF) for all the sequenced indexes. 

Basically I am looking for all the indexes sequenced or maybe top 1000.

Thanks.

**Comment by ezralanglois** [comment]
Do you mean the top unknown bar codes? If so, those are not stored in the InterOp file.

**Comment by Nitin123-4** [comment]
Okay, Basically what I wanted to look for if I can get top 1000 barcodes and reads or % Reads Identified (PF) for them before even doing demultiplexing. This way I can use this information for some checks.

So basically if we can get All or top 1000 indexes which shows reads in the run.

**Comment by ezralanglois** [comment]
Do those barcodes all show up in the samplesheet?

**Comment by Nitin123-4** [comment]
No. Is it possible to get even if sample sheet is not there?
I mean from the run folder only can we get this information?
Thanks.

**Comment by ezralanglois** [comment]
InterOp requires the `IndexMetricsOut.bin` to be in the InterOp subdirectory of the run folder.
`IndexMetricsOut.bin` only contains information on the barcodes in the samplesheet

**Comment by Nitin123-4** [comment]
Okay. 

Is there any way you recommand to get the information?

Thanks for your quick response.

**Comment by ezralanglois** [comment]
Not with this library.

Check out this page: https://support.illumina.com/sequencing/sequencing_software/bcl-convert/documentation.html

**Comment by tamuanand** [comment]
> I think you are looking for this https://github.com/Illumina/interop/blob/master/docs/src/Tutorial_04_Indexing_Metrics.ipynb
> 
> Be aware that the IndexMetricsOut.bin is not produced by RTA. It is produced by the bcl conversion software. On some systems, it needs to be moved into the InterOp directory manually if it is not already there.

Hi @ezralanglois 

The above python notebook link is not working. Request you to share the correct link

Thanks
