### ISSUE TITLE
pip install is version 1.1.23?

### ISSUE THREAD

**Issue by dmcmanam** [Illumina/interop#328]
I would like to install the latest version to read NovaSeqX files but pip install only has up to version 1.1.23?  Can you update the build from source instructions to include directions for making the current python bindings?

**Comment by ezralanglois** [comment]
I see it up there. 
https://pypi.org/project/interop/#files

What version of python and OS are you looking for?

**Comment by dmcmanam** [comment]
I'm looking for Linux CentOS 7, any version of python 3.

**Comment by ezralanglois** [comment]
Do you have 1.1.23 already installed?

**Comment by dmcmanam** [comment]
Yes, 

pip show interop
Name: interop
Version: 1.1.23

**Comment by ezralanglois** [comment]
When you want to update a python package with pip you have to add `-U`

For example `pip install -U interop`. This is likely why it is not updating

**Comment by dmcmanam** [comment]
So far I still haven't installed the current version.  For example:

pip install interop==1.2.4

ERROR: Could not find a version that satisfies the requirement
interop==1.2.4 (from versions: 1.1.18, 1.1.19, 1.1.21, 1.1.22, 1.1.23)

ERROR: No matching distribution found for interop==1.2.4

**Comment by ezralanglois** [comment]
The reasons pip could fail are:
1. pip not configured properly
2. You are running an ARM chip
3. You have an unsupported version of python3

I did a test with the latest CentOS 7 docker image (after installing python3 from yum).

```
[root@566f65e778dd tmp]# pip3 install interop
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting interop
  Downloading https://files.pythonhosted.org/packages/06/f2/060f837f66d6c4acaf8f9153ac63c05446b76913f10ecd7336533cde1211/interop-1.2.4-cp36-cp36m-manylinux1_x86_64.whl (4.2MB)
    100% |################################| 4.2MB 345kB/s 
Collecting numpy>=1.16.6; python_version >= "3.5" (from interop)
  Downloading https://files.pythonhosted.org/packages/45/b2/6c7545bb7a38754d63048c7696804a0d947328125d81bf12beaa692c3ae3/numpy-1.19.5-cp36-cp36m-manylinux1_x86_64.whl (13.4MB)
    100% |################################| 13.4MB 101kB/s 
Installing collected packages: numpy, interop
Successfully installed interop-1.2.4 numpy-1.19.5
```

We don't support python 3.11 yet, otherwise maybe you can find the wheel here: https://pypi.org/project/interop/#files

**Comment by dmcmanam** [comment]
Thank you, I upgraded to python 3.10 and now everything is working fine.
