### ISSUE TITLE
AlignmentMetricsOut.bin and IndexMetricsOut.bin mapping information

### ISSUE THREAD

**Issue by NateBaileyTempus** [Illumina/interop#329]
I was wondering if you had the mapping details for these file types and the other .bin files not included in github so we could parse ourselves?

**Comment by ezralanglois** [comment]
This library parses IndexMetricsOut.bin. 

All the binary formats are described here for supported formats: https://illumina.github.io/interop/binary_formats.html

The AlignmentMetricsOut.bin is not supported.

**Comment by NateBaileyTempus** [comment]
Thanks for the swift reply!
Have a parallel question in tech support asking after the binary map info for AlignmentMetricsOut.bin to parse the data ourselves. Do you happen to know where this info might be?
-Nate

**Comment by NateBaileyTempus** [comment]
Thanks! closing, but will update for other folks to find the map if i do get an answer.
