### ISSUE TITLE
interop-summary: description of columns

### ISSUE THREAD

**Issue by nick-youngblut** [Illumina/interop#339]
It would be helpful if https://illumina.github.io/interop/summary_table.html (and/or the summary cli help docs) included a description of the columns.

For instance, is `Reads PF` actually `% Pass Filter` as in https://github.com/Illumina/interop/blob/520e8ab8a5a3f3d5fa44ab4d32643fb7c6da0b30/src/apps/imaging_table.cpp#L15? 

The same goes for other columns such as whether `Density` k/mm^2, as in https://github.com/Illumina/interop/blob/520e8ab8a5a3f3d5fa44ab4d32643fb7c6da0b30/src/apps/imaging_table.cpp#L15?

**Comment by ezralanglois** [comment]
InterOp provides all the metrics for Sequencing Analysis Viewer (SAV). The SAV documentation has the description for each metric and can be found here:
https://support-docs.illumina.com/SW/SAV/Content/SW/SAV/Metrics.htm

**Comment by nick-youngblut** [comment]
Thanks @ezralanglois ! Maybe it would be helpful to include a link to the metrics page at https://illumina.github.io/interop/summary_table.html?
