### ISSUE TITLE
Can I get all the index information

### ISSUE THREAD

**Issue by Nitin123-4** [Illumina/interop#342]
Hi All,

Can I get all the index and reads generated information from InterOP folder?

Provided I don't have sample sheet there. I just want to know without sample sheet top 1000 indexes.

The idea is can we get the top 1000 index with reads information without running bcl2fastq or bcl-convert?

**Comment by ezralanglois** [comment]
That information is not written to a binary interop file. It is available in the reports of both programs, depending how they are configured

**Comment by Nitin123-4** [comment]
It will be helpful if somehow we can get this information without running bcl2fastq or bcl-convert as it takes time to parse bbl files.

Thanks.

**Comment by ezralanglois** [comment]
Those metrics are all produced by bclconvert/bcl2fastq (not RTA). So you have to run those tools to get the metrics
