### ISSUE TITLE
C# Percentage > Q30 by cycle graph

### ISSUE THREAD

**Issue by IIID-Don** [Illumina/interop#344]
Where can I find the data to produce the Percentage greater than Q30 graph as produced on the overview tab of the SAV.

Do I need to calculate it from the imaging table data?

Thanks

Don

**Comment by ezralanglois** [comment]
See https://github.com/Illumina/interop/issues/198

**Comment by IIID-Don** [comment]
Thanks ezralanglois,

I managed to get there, but have two questions:
1) What is the C# equivalent of the python command: interop_run.MetricCount
2) When I plot the graph, the SAV Average percent >= Q30 plot on the Overview tab, appears to be the same data as the maximum percent >= Q30, that I got from the interop, should that be the case?

Don

**Comment by IIID-Don** [comment]
Thanks Robert,

I originally plotted it as a candlestick, but it was too busy. Also on the Illumina SAV it is not plotted as a candlestick, presumably for the same reason (see image attached). I decided to use candle_stick_point.p50() which appears to be the same as candle_stick_point.y(), but my chart/graph did not match that on the SAV. By hovering over the points on the SAV to see their values, I deduced that the SAV is plotting candle_stick_point.max_value(). 
I would have thought that either the mean / average (which I can't find in candle_stick_point) or the median (y or p50) would have been better to plot than the maximum (max_value). Do you know why the max_value was chosen in the SAV for this plot? Or have I misunderstood?

Thanks

Don
<img width="2480" alt="Screenshot 2024-05-14 at 09 04 40" src="https://github.com/Illumina/interop/assets/169324665/723c4525-2589-40ad-ad57-5382825b4894">

**Comment by ezralanglois** [comment]
You would have to reach out to Illumina support. I don't work on SAV and cannot comment on the choices they made.

**Comment by IIID-Don** [comment]
Thanks Robert,

I have decided that plotting the median is best for my purposes.

I appreciate the help you have given me for using the interop. I'm able to achieve what I set out to do, thanks to this project and your assistance.

All the best

Don
