### ISSUE TITLE
Docs and/or support for novaseqx interops files e.g. ImageQualityMetricsOut.bin

### ISSUE THREAD

**Issue by accopeland** [Illumina/interop#351]
Hi,

NovaSeqX run directories contain a number of '.bin' files which don't appear to be supported or documented in this repo. I am not sure if they even qualify as 'Interop' files since I can't find any descriptions for them. Nevertheless, I am wondering if they will be described and supported at some point. The files in question are:

AlignmentMetricsOut.bin
BasecallingMetricsOut.bin
EmpiricalPhasingMetricsOut.bin
EventMetricsOut.bin
FWHMGridMetricsOut.bin
ImageQualityMetricsOut.bin
InsertSizeMetricsOut.bin
OpticalMetricsOut.bin
OpticalModelMetricsOut.bin
PFGridMetricsOut.bin
RegistrationMetricsOut.bin
RunInfoMetricsOut.bin

Thanks,
Alex

**Comment by ezralanglois** [comment]
None of those files are covered by this repo.
