### ISSUE TITLE
The best way to extract per tile data for plotting %Occupied by %PF 

### ISSUE THREAD

**Issue by SQYSunny** [Illumina/interop#352]
Hello, I have some Nextseq2000 run data and I need to generate a report to include a scatter plot that shows % Occupied by % PF,  like the plot created in SAV. I have tried to do it using interop in python a bit:
```
run_folder='/my_run_folder'
from interop import py_interop_run_metrics, py_interop_summary, py_interop_run
run_metrics = py_interop_run_metrics.run_metrics()
valid_to_load = py_interop_run.uchar_vector(py_interop_run.MetricCount, 0)
py_interop_run_metrics.list_analysis_metrics_to_load(valid_to_load)

run_metrics.read(run_folder, valid_to_load)
tile_metric_set = run_metrics.tile_metric_set()
```

I was able to check certain information like `tile_metric_set.size()` which returns 132, but I am wondering if what I have done was correct and how I can extract per tile info from this? If someone can help that would be greatly appreciated!

**Comment by ezralanglois** [comment]
The easiest way is to do something like this
https://gist.github.com/ezralanglois/81d43c02f751579a2057f913238e7a2a

That examples shows error rate, but occupancy and PF will also be columns in the dataframe.

**Comment by SQYSunny** [comment]
> The easiest way is to do something like this https://gist.github.com/ezralanglois/81d43c02f751579a2057f913238e7a2a
> 
> That examples shows error rate, but occupancy and PF will also be columns in the dataframe.

Thank you Robert! I followed the script to use interop.core and it was showing PF data, but it is not showing per tile data point, I am trying to create something like this in a QC report:
![image](https://github.com/user-attachments/assets/51d8e4c7-e9ce-46bf-af47-a13bbd6c8ef5)

Do you know what would be the way to get per tile %PF and %Occupied info?

**Comment by ezralanglois** [comment]
Yes, you will need to filter the data frame to a single cycle
`df_tile = df[df['Cycle'] == 1]`

then select the columns you want

columns = ['% Pass filter', '% Occupied']
df_tile = df_tile[columns]

**Comment by SQYSunny** [comment]
Thank you so much Robert! Would you mind pointing out how the `df` was created? was it by `interop.core.summary`? I was following your script in the `error_rate_summary.py` by:
`df_summary = pd.DataFrame(interop.core.summary(run_folder, level='Lane'))`

The output df_summary does not have 'Cycle' column though.
I also tried different levels including `'Total', 'NonIndex', 'Read', 'Lane', 'Surface'`, but none of these look like what I am expecting.

**Comment by ezralanglois** [comment]
Ah, apologies, I gave you the summary example

You should be using `imaging`

Here are some pointers to some examples

https://github.com/Illumina/interop/issues/286

**Comment by SQYSunny** [comment]
Thank you so much for the help @ezralanglois ! I was able to get the data as you mentioned.

Just a final summary in case anyone is working on a similar analysis:

`from interop import *
df = pd.DataFrame(imaging(path_to_run_dir))
df_tile = df[df['Cycle'] == 1].reset_index(drop=True)`

And the output df contains these columns:

`['Lane', 'Tile', 'Cycle', 'Read', 'Cycle Within Read', 'Density(k/mm2)',
       'Density Pf(k/mm2)', 'Cluster Count (k)', 'Cluster Count Pf (k)',
       '% Pass Filter', '% Aligned', 'Legacy Phasing Rate',
       'Legacy Prephasing Rate', 'Error Rate', '%>= Q20', '%>= Q30',
       'P90/green', 'P90/blue', '% No Calls', '% Base/A', '% Base/C',
       '% Base/G', '% Base/T', 'Fwhm/green', 'Fwhm/blue', 'Corrected/A',
       'Corrected/C', 'Corrected/G', 'Corrected/T', 'Called/A', 'Called/C',
       'Called/G', 'Called/T', 'Signal To Noise', 'Phasing Weight',
       'Prephasing Weight', 'Phasing Slope', 'Phasing Offset',
       'Prephasing Slope', 'Prephasing Offset', 'Minimum Contrast/green',
       'Minimum Contrast/blue', 'Maximum Contrast/green',
       'Maximum Contrast/blue', 'Surface', 'Swath', 'Tile Number',
       'Cluster Count Occupied (k)', '% Occupied']`
