### ISSUE TITLE
summary - RunParameters.xml required for legacy run folders and is missing

### ISSUE THREAD

**Issue by kevyin** [Illumina/interop#49]
Hey there
Thanks a bunch for adding summary!

atm I get this error on some recent HS2500 and HSX runfolders

> RunParameters.xml required for legacy run folders and is missing

Our runfolders have a runParameters.xml
When I rename this to RunParameters.xml
summary runs fine

It seems all of our runfolders have the lower case r for this file

Thanks again for library!

**Comment by ezralanglois** [comment]
Hi Kevin,

Thanks for reporting this issue. We do most of our regression tests on Windows, so we missed this case. I will work on a fix. I am preparing another release once some other odds and ends get in, this bug fix will go into that release (as well as master).

Thanks.
