### ISSUE TITLE
MiSeq - the QScores are 100% which obviously isn't reflected in the data.

### ISSUE THREAD

**Issue by ezralanglois** [Illumina/interop#53]
Creating another issue to take this item originally reported in: https://github.com/Illumina/interop/issues/52

Reported by @markliexo

**Comment by ezralanglois** [comment]
I just released InterOp v1.0.5. This bug fix may (or may not) take care of the problem reported by @markliexo

**Comment by markliexo** [comment]
Looking at our last MiSeq run, the scores went from 100% to 95.25% in Read 1 and 96.38% in Read 2 which matches the SAV. Thanks for such a quick fix. 

I am looking at the data as it comes off the sequencer, so will keep an eye on it for the next run which hopefully will be soon. 

Thanks! 

Mark

**Comment by ezralanglois** [comment]
Great, thanks for letting me know. I will leave this ticket open until Monday. If you run into any more problems (after Monday), then you can file another one or reopen this one.
