### ISSUE TITLE
Update cycle state for other metrics

### ISSUE THREAD

**Issue by ezralanglois** [Illumina/interop#54]
Currently, only the error rated cycle state is updated. The rest should be updated too.

**Comment by markliexo** [comment]
I can extract the MISeq current cycle from the xml files. And that works pretty well. The same file is not written for the NextSeq. Is that information possible to add for summary script?

**Comment by ezralanglois** [comment]
I can give you the current cycle, roughly for extraction, basecalling and q-scoring subject to the caveat that it may not be as exact as the RunState.xml on MiSeq systems. 

It may lag behind some. That is the best I can do on the modern systems.

I will start working on adding this functionality sometime next week.

**Comment by ezralanglois** [comment]
I am testing the functionality for this now. This could take a little time to ensure there are no bugs.

**Comment by markliexo** [comment]
Great. Thanks.
