### ISSUE TITLE
Compiling an example

### ISSUE THREAD

**Issue by ofedrigo** [Illumina/interop#56]
Hi,

I have downloaded the Linux precompiled library and have tried to compile an example code:
`gcc -Iinterop/include/ test.cpp interop/lib64/libinterop_lib.a -o test`

but I get this error message:
/tmp/ccr1iTvq.o:(.eh_frame+0x2eb): undefined reference to `__gxx_personality_v0'
collect2: error: ld returned 1 exit status

I apologize in advance if my question is naive.

Thank you,

Olivier

**Comment by ezralanglois** [comment]
Hi Oliver,

This is not a naive question. I actually expected to get this question at 

Currently, we use TravisCI to build the binary and made the decision, for now, to go with the native GCC (GCC 4.6). Also, Travis uses a Debian flavor of Linux.

It would help to know your version of Linux and GCC version (gcc --version) to help diagnose the problem better.

My guess is, either you are using an older or much newer gcc or your flavor of Linux is not compatible.

We do plan to create a version that is compatible with most versions of Linux, but this is a lower priority item at the moment.

Best.

**Comment by ofedrigo** [comment]
Robert,

Thank you very much for your email.

Herere is the GCC version we use:
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)

Olivier

Olivier Fedrigo
Director, Genome Sequencing Shared Resource 
Duke Center for Genomic and Computational Biology
Duke University

T. 919-684-6730 F. 919-660-7293
email: ofedrigo@duke.edu
Consultation Scheduling : https://sequencing_olivierfedrigo.youcanbook.me
Web: http://www.genome.duke.edu/cores/sequencing/
FAQs: http://www.genome.duke.edu/cores/sequencing/faq/
Order Tracking: http://seqweb.igsp.duke.edu/internal/Tracker.html

From:  Robert Langlois
Reply-To:  Illumina/interop
Date:  Monday, April 18, 2016 at 1:23 PM
To:  Illumina/interop
Cc:  Olivier Fedrigo
Subject:  Re: [Illumina/interop] Compiling an example (#56)


Hi Oliver,

This is not a naive question. I actually expected to get this question at 

Currently, we use TravisCI to build the binary and made the decision, for now, to go with the native GCC (GCC 4.6). Also, Travis uses a Debian flavor of Linux.

It would help to know your version of Linux and GCC version (gcc --version) to help diagnose the problem better.

My guess is, either you are using an older or much newer gcc or your flavor of Linux is not compatible.

We do plan to create a version that is compatible with most versions of Linux, but this is a lower priority item at the moment.

Best.

**Comment by ezralanglois** [comment]
Hi Oliver,

Based on your gcc version, this error seems strange. I looked at the command line you provided closer and see you are using gcc instead of g++.

First, I want to make sure I did not mistakenly include that on the site somewhere, do you remember were you found that line?

Second, you will not be able to link with gcc unless you provide some additional arguments, e.g. linking to the c++ library -lstdc++.

Best.
