### ISSUE TITLE
clusterDensity value

### ISSUE THREAD

**Issue by rglandie** [Illumina/interop#58]
Hi, 

I try to calculate clusterDensity value . SAV return a value of 2355 (K / mm ) and the function clusterDensity : 2.35491x10 ^ 6 .
In function definition we have:
Density of clusters For Each tile (in Thousands per mm2). So if the return value is in Thousands per mm² we have a value of density equal to 2354.91x10 ^ 3 k / mm². It's a big difference . The return value of this function is really in Thousands per mm² ?

**Comment by ezralanglois** [comment]
The documentation for the clusterDensity function in tile_metrics is wrong (I am fixing it with https://github.com/Illumina/interop/pull/59). The value stored in tile metrics is the cluster density, but the value reported by SAV is per thousand clusters.

So, you just need to divide the cluster density value by 1e3 and it should report the proper value.

On line 259 of https://github.com/Illumina/interop/blob/master/src/apps/summary.cpp, you can see that the summary program (which reports the same numbers as SAV) does the same thing.
