### ISSUE TITLE
recover Cycles err rated informations

### ISSUE THREAD

**Issue by rglandie** [Illumina/interop#62]
I need to recover cycles err rated informations. Because sometimes we don't have 150 but 0-150 in this metric. I need to know when this happened to adapt my script. Can you help me ?

**Comment by ezralanglois** [comment]
I would look at https://github.com/Illumina/interop/blob/master/src/apps/summary.cpp to get this information.

In brief, you need to create run metrics, read in the InterOp files and then populate the summary model:
 run_metrics run;
run_summary summary;
run.read("/run-folder");
summarize_run_metrics(run, summary);

Then you can get the information for each read or overall.

For example for read 1, lane 2, you would do the following to get the first cycle:

summary[1][2].cycle_state().error_cycle_range().first_cycle()

And the following to get the last cycle:

summary[1][2].cycle_state().error_cycle_range().last_cycle()

**Comment by rglandie** [comment]
Thanks for your help. Can you add density passing filter (function: clusterDensityPf()) in script summary.cpp ?

**Comment by ezralanglois** [comment]
The summary application is supposed to mimic the SAV summary tab. You can add this to your own copy by replacing line 259:
values[2] = format(summary.density(), 0, 0, 1e3);

with:
values[2] = format(summary.density_pf(), 0, 0, 1e3);

And then update the description on line 300 accordingly.

Alternatively, you could just add another column by adding to the description and updating the function on line 259. If you go this route, ensure the column description matches the values array or you will have segfaults.
