### ISSUE TITLE
interop haven't support for Illumina MiniSeq of index-summary

### ISSUE THREAD

**Issue by libranjie** [Illumina/interop#88]
For Illumina MiSeq, interop have index-summary function, however, there is no result with MiniSeq run.

`# Version: v1.0.12
Lane 1
 Total Reads     PF Reads        % Read Identified (PF) CV              Min             Max            
 0               0               0.0000          -nan            0.0000          0.0000         
 Index Number    Sample Id       Project         Index 1 (I7)    Index 2 (I5)    % Read Identified (PF)`

**Comment by ezralanglois** [comment]
Hi. Thanks for the bug report. Could you provide the InterOp folder and the RunInfo.xml?
I would be happy to look into this issue.

Best,
Rob

**Comment by libranjie** [comment]
[160623_MN00302_0001_A000H02FHM.tar.gz](https://github.com/Illumina/interop/files/554791/160623_MN00302_0001_A000H02FHM.tar.gz)

Thanks, in my opinion, this may due to fact that MiniSeq have no "IndexMetricsOut.bin" and what's more, the plot_by_cycle only draw the signal of red and green, but not the base ATCG. 
![161011_mn00302_0008_a000h225tv_intensity-by-cycle_intensity](https://cloud.githubusercontent.com/assets/17739584/19754084/ec19c11c-9bcf-11e6-80d2-4825eab63a8d.png)

**Comment by ezralanglois** [comment]
On a MiSeq, index metrics is written out by RTA.
On a MiniSeq, index metrics is written out when you run bcl2fastq (or the secondary analysis pipe line ISAS).

As for the By Cycle Plot, the MiSeq is a 4 channel system, where each channel is labeled with a base. So, you get 4 intensity curves labeled by each base.

The MiniSeq is a 2 channel system, where each channel is labeled by the color of the laser. So, you get 2 intensity curves labeled by the color.

The bases are actually derived in a different manner, you can see this document below (Figure 2), for more information.

http://www.illumina.com/content/dam/illumina-marketing/documents/products/techspotlights/techspotlight_two-channel_sbs.pdf

**Comment by ezralanglois** [comment]
I will add a better error message to the index summary in the next release.
