### ISSUE TITLE
Unknown tile naming method - update your RunInfo.xml

### ISSUE THREAD

**Issue by awchrist** [Illumina/interop#89]
I'm having trouble generating a few of the plots for data that was produced on our older HiSeq2000/2500. Data off the 4k makes the BasePercent and others just fine, but I can tell the RunInfo.xml is formatted differently. 
Here is the error I'm getting.
plot_by_cycle ./160420_7001452_0296_AC8GJ5ANXX/ --metric-name=BasePercent
Version: v1.0.12
Run Folder: 160420_7001452_0296_AC8GJ5ANXX
Unknown tile naming method - update your RunInfo.xml
/var/tmp/linux_gcc46_release/interop/src/interop/model/run_metrics.cpp::finalize_after_load (436)

and here is the RunInfo.xml, runParameters.xml, and InterOp files.
[160420_7001452_0296_AC8GJ5ANXX.tar.gz](https://github.com/Illumina/interop/files/614742/160420_7001452_0296_AC8GJ5ANXX.tar.gz)

Am I just missing an additional step? 
I've seen some other examples of the RunInfo.xml online that look just like mine so I don't think they are bad, other than the fact they are an older version.
RunInfo xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Version="2"

Thanks

**Comment by ezralanglois** [comment]
Hi Austin,

I appreciate the comprehensive bug report. I was able to reproduce the problem. This is definitely a bug.
