### ISSUE TITLE
File Format Description

### ISSUE THREAD

**Issue by sklages** [Illumina/interop#96]
Hi,

kind of "feature request": It would be nice to see the (current) InterOp file format description for each of the bin files here as well (without compiling the sources). 

E.g.
```
    # Quality Metrics (QualityMetricsOut.bin)
    # Contains quality score distribution
    # Format, version 5 (NxSeq500 and newer):
    #  byte 0: file version number (5)
    #  byte 1: length of each record
    #  byte 2: quality score binning (byte flag representing if binning was on)
    #  byte 3: number of quality score bins, B
    #  bytes 4 - (4+B-1): lower boundary of quality score bins
    #  bytes (4+B) - (4+2*B-1): upper boundary of quality score bins
    #  bytes (4+2*B) - (4+3*B-1): remapped scores of quality score bins
    #
    #  The remaining bytes are for the records, with each record in this format:
    #   2 bytes: lane number  (uint16)
    #   2 bytes: tile number  (uint16)
    #   2 bytes: cycle number (uint16)
    #   4 x 50 bytes: number of clusters assigned score (uint32) Q1 through Q50
    #   Where N is the record index
```
That makes it pretty complete. And I don't have to search in almost forgotten PDF files for the descriptions ;-)

best,
Sven

**Comment by ezralanglois** [comment]
Hi Sven,

We do have the formats at the following location:
http://illumina.github.io/interop/binary_formats.html

Will this work for you?

It does seem a link from the main page would make it easier to find, I will leave this issue open until I find some time to add it.

Best,
Rob

**Comment by sklages** [comment]
Hi Rob,

sure, that's perfect! 
A link on the main page would be very helpful indeed 👍 

thanks,
Sven

**Comment by ezralanglois** [comment]
I just updated the docs to add the Formats link.

Best,
Rob
