### ISSUE TITLE
Please include docs for dumptext

### ISSUE THREAD

**Issue by gourneau** [Illumina/interop#98]
Hi folks,

It looks like the docs at http://illumina.github.io/interop/index.html are 1 release behind at `InterOp v1.0.13-2-gc534deb`

Specifically the [applications](http://illumina.github.io/interop/apps.html) page does not yet have help for the new `dumptext` application. Could y'all please add them :)

I would also like to register my interest in another release. Release v1.0.14 had some fatal bugs in `dumptext` that were fixed with https://github.com/Illumina/interop/pull/97 which caused me a lot of confusion.

Thanks so much!

**Comment by ezralanglois** [comment]
I just pushed up the changes to the docs:
http://illumina.github.io/interop/dumptext.html

I will kick off a new release too. Should be done in a few hours.

Best,
Rob

**Comment by ezralanglois** [comment]
Thanks for the feedback, it looks like everything here is fixed.
