### ISSUE TITLE
NextSeq dumptext error

### ISSUE THREAD

**Issue by gourneau** [Illumina/interop#99]
`dumptext` seems to work for the example MiSeq data all the HiSeq data I have tried to use it against.

However, with NextSeq InterOp files I am experiencing problems. This is with the 1.0.15 release (thanks so much for that!)

The problem seems to happen at the start of the `#Extraction` section

```
# Extraction,1
Header and channel names count mismatch
/home/travis/build/Illumina/interop/src/interop/model/metrics/extraction_metric.cpp::write_header (190)
```

I was able to replicate this error with a public dataset "NextSeq 500 v2: Nextera Rapid Capture Exome (CEPH 9plex) - H3GJKBGX"  Which you can find the InterOp files here https://figshare.com/articles/NextSeq_500_InterOp_example_data/4564000

**Comment by ezralanglois** [comment]
Thanks for the report. I was able to reproduce the problem.
